module NPU_PSUM_PORT
    #(
`ifdef EMULATION
        parameter [639:0] Tile_X0Y0_Emulate_Bitstream=640'b0,
        parameter [639:0] Tile_X1Y0_Emulate_Bitstream=640'b0,
`endif
        parameter MaxFramesPerCol=20,
        parameter FrameBitsPerRow=32
    )
    (
    //Tile_X0Y0_Direction.NORTH
        input  [3:0] Tile_X0Y0_N1END, //TilePort({S} INPUT N1END[3:0])
        input  [7:0] Tile_X0Y0_N2MID, //TilePort({S} INPUT N2MID[7:0])
        input  [7:0] Tile_X0Y0_N2END, //TilePort({S} INPUT N2END[7:0])
        input  [15:0] Tile_X0Y0_N4END, //TilePort({S} INPUT N4END[3:0])
        input  [15:0] Tile_X0Y0_NN4END, //TilePort({S} INPUT NN4END[3:0])
        output  [3:0] Tile_X0Y0_S1BEG, //TilePort({S} OUTPUT S1BEG[3:0])
        output  [7:0] Tile_X0Y0_S2BEG, //TilePort({S} OUTPUT S2BEG[7:0])
        output  [7:0] Tile_X0Y0_S2BEGb, //TilePort({S} OUTPUT S2BEGb[7:0])
        output  [15:0] Tile_X0Y0_S4BEG, //TilePort({S} OUTPUT S4BEG[3:0])
        output  [15:0] Tile_X0Y0_SS4BEG, //TilePort({S} OUTPUT SS4BEG[3:0])
        input  [0:0] Tile_X0Y0_Ci, //TilePort({S} INPUT Ci[0:0])
    //Tile_X1Y0_Direction.NORTH
        input  [3:0] Tile_X1Y0_N1END, //TilePort({S} INPUT N1END[3:0])
        input  [7:0] Tile_X1Y0_N2MID, //TilePort({S} INPUT N2MID[7:0])
        input  [7:0] Tile_X1Y0_N2END, //TilePort({S} INPUT N2END[7:0])
        input  [15:0] Tile_X1Y0_N4END, //TilePort({S} INPUT N4END[3:0])
        input  [15:0] Tile_X1Y0_NN4END, //TilePort({S} INPUT NN4END[3:0])
        output  [3:0] Tile_X1Y0_S1BEG, //TilePort({S} OUTPUT S1BEG[3:0])
        output  [7:0] Tile_X1Y0_S2BEG, //TilePort({S} OUTPUT S2BEG[7:0])
        output  [7:0] Tile_X1Y0_S2BEGb, //TilePort({S} OUTPUT S2BEGb[7:0])
        output  [15:0] Tile_X1Y0_S4BEG, //TilePort({S} OUTPUT S4BEG[3:0])
        output  [15:0] Tile_X1Y0_SS4BEG, //TilePort({S} OUTPUT SS4BEG[3:0])
        input  [0:0] Tile_X1Y0_Ci, //TilePort({S} INPUT Ci[0:0])
    //Tile IO ports from BELs
    //SuperTile BEL IO ports
        input  NPU_RDATA0,
        input  NPU_RDATA1,
        input  NPU_RDATA2,
        input  NPU_RDATA3,
        input  NPU_RDATA4,
        input  NPU_RDATA5,
        input  NPU_RDATA6,
        input  NPU_RDATA7,
        input  NPU_RDATA8,
        input  NPU_RDATA9,
        input  NPU_RDATA10,
        input  NPU_RDATA11,
        input  NPU_RDATA12,
        input  NPU_RDATA13,
        input  NPU_RDATA14,
        input  NPU_RDATA15,
        input  NPU_RDATA16,
        input  NPU_RDATA17,
        input  NPU_RDATA18,
        input  NPU_RDATA19,
        input  NPU_RDATA20,
        input  NPU_RDATA21,
        input  NPU_RDATA22,
        input  NPU_RDATA23,
        input  NPU_RDATA24,
        input  NPU_RDATA25,
        input  NPU_RDATA26,
        input  NPU_RDATA27,
        input  NPU_RDATA28,
        input  NPU_RDATA29,
        input  NPU_RDATA30,
        input  NPU_RDATA31,
        output  NPU_ADDR0,
        output  NPU_ADDR1,
        output  NPU_ADDR2,
        output  NPU_ADDR3,
        output  NPU_ADDR4,
        output  NPU_ADDR5,
        output  NPU_ADDR6,
        output  NPU_ADDR7,
        output  NPU_WE0,
        output  NPU_WE1,
        output  NPU_WE2,
        output  NPU_WE3,
        output  NPU_WE4,
        output  NPU_WE5,
        output  NPU_WE6,
        output  NPU_WE7,
        output  NPU_WDATA0,
        output  NPU_WDATA1,
        output  NPU_WDATA2,
        output  NPU_WDATA3,
        output  NPU_WDATA4,
        output  NPU_WDATA5,
        output  NPU_WDATA6,
        output  NPU_WDATA7,
        output  NPU_WDATA8,
        output  NPU_WDATA9,
        output  NPU_WDATA10,
        output  NPU_WDATA11,
        output  NPU_WDATA12,
        output  NPU_WDATA13,
        output  NPU_WDATA14,
        output  NPU_WDATA15,
        output  NPU_WDATA16,
        output  NPU_WDATA17,
        output  NPU_WDATA18,
        output  NPU_WDATA19,
        output  NPU_WDATA20,
        output  NPU_WDATA21,
        output  NPU_WDATA22,
        output  NPU_WDATA23,
        output  NPU_WDATA24,
        output  NPU_WDATA25,
        output  NPU_WDATA26,
        output  NPU_WDATA27,
        output  NPU_WDATA28,
        output  NPU_WDATA29,
        output  NPU_WDATA30,
        output  NPU_WDATA31,
        output  NPU_READ_BANK_SEL0,
        output  NPU_READ_BANK_SEL1,
        output  NPU_READ_BANK_SEL2,
        output  [MaxFramesPerCol-1:0] Tile_X0Y0_FrameStrobe_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y0_FrameData, //CONFIG_PORT
        input  [MaxFramesPerCol-1:0] Tile_X0Y0_FrameStrobe, //CONFIG_PORT
        output  [MaxFramesPerCol-1:0] Tile_X1Y0_FrameStrobe_O, //CONFIG_PORT
        input  [MaxFramesPerCol-1:0] Tile_X1Y0_FrameStrobe, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X1Y0_FrameData_O, //CONFIG_PORT
        output  Tile_X0Y0_UserCLKo,
        input  Tile_X0Y0_UserCLK,
        output  Tile_X1Y0_UserCLKo,
        input  Tile_X1Y0_UserCLK
);

 //signal declarations
 //SJUMP signals (child tile -> supertile SM)
    wire[32-1:0] NPU_PSUM_PORT0_BASE_TO_TOP;
    wire[19-1:0] NPU_PSUM_PORT1_BASE_TO_TOP;
 //SJUMP signals (supertile SM -> child tile)
    wire[16-1:0] NPU_PSUM_PORT0_TOP_TO_BASE;
    wire[16-1:0] NPU_PSUM_PORT1_TOP_TO_BASE;
 //BEL pin signals (BEL <-> supertile SM)
    wire FAB_ADDR0;
    wire FAB_ADDR1;
    wire FAB_ADDR2;
    wire FAB_ADDR3;
    wire FAB_ADDR4;
    wire FAB_ADDR5;
    wire FAB_ADDR6;
    wire FAB_ADDR7;
    wire FAB_WE0;
    wire FAB_WE1;
    wire FAB_WE2;
    wire FAB_WE3;
    wire FAB_WE4;
    wire FAB_WE5;
    wire FAB_WE6;
    wire FAB_WE7;
    wire FAB_WDATA0;
    wire FAB_WDATA1;
    wire FAB_WDATA2;
    wire FAB_WDATA3;
    wire FAB_WDATA4;
    wire FAB_WDATA5;
    wire FAB_WDATA6;
    wire FAB_WDATA7;
    wire FAB_WDATA8;
    wire FAB_WDATA9;
    wire FAB_WDATA10;
    wire FAB_WDATA11;
    wire FAB_WDATA12;
    wire FAB_WDATA13;
    wire FAB_WDATA14;
    wire FAB_WDATA15;
    wire FAB_WDATA16;
    wire FAB_WDATA17;
    wire FAB_WDATA18;
    wire FAB_WDATA19;
    wire FAB_WDATA20;
    wire FAB_WDATA21;
    wire FAB_WDATA22;
    wire FAB_WDATA23;
    wire FAB_WDATA24;
    wire FAB_WDATA25;
    wire FAB_WDATA26;
    wire FAB_WDATA27;
    wire FAB_WDATA28;
    wire FAB_WDATA29;
    wire FAB_WDATA30;
    wire FAB_WDATA31;
    wire FAB_READ_BANK_SEL0;
    wire FAB_READ_BANK_SEL1;
    wire FAB_READ_BANK_SEL2;
    wire FAB_RDATA0;
    wire FAB_RDATA1;
    wire FAB_RDATA2;
    wire FAB_RDATA3;
    wire FAB_RDATA4;
    wire FAB_RDATA5;
    wire FAB_RDATA6;
    wire FAB_RDATA7;
    wire FAB_RDATA8;
    wire FAB_RDATA9;
    wire FAB_RDATA10;
    wire FAB_RDATA11;
    wire FAB_RDATA12;
    wire FAB_RDATA13;
    wire FAB_RDATA14;
    wire FAB_RDATA15;
    wire FAB_RDATA16;
    wire FAB_RDATA17;
    wire FAB_RDATA18;
    wire FAB_RDATA19;
    wire FAB_RDATA20;
    wire FAB_RDATA21;
    wire FAB_RDATA22;
    wire FAB_RDATA23;
    wire FAB_RDATA24;
    wire FAB_RDATA25;
    wire FAB_RDATA26;
    wire FAB_RDATA27;
    wire FAB_RDATA28;
    wire FAB_RDATA29;
    wire FAB_RDATA30;
    wire FAB_RDATA31;
    wire[FrameBitsPerRow-1:0] Tile_X0Y0_FrameData_O;

NPU_PSUM_PORT0
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y0_Emulate_Bitstream)
    )
`endif
    Tile_X0Y0_NPU_PSUM_PORT0
    (
    .N1END(Tile_X0Y0_N1END),
    .N2MID(Tile_X0Y0_N2MID),
    .N2END(Tile_X0Y0_N2END),
    .N4END(Tile_X0Y0_N4END),
    .NN4END(Tile_X0Y0_NN4END),
    .Ci(Tile_X0Y0_Ci),
    .S1BEG(Tile_X0Y0_S1BEG),
    .S2BEG(Tile_X0Y0_S2BEG),
    .S2BEGb(Tile_X0Y0_S2BEGb),
    .S4BEG(Tile_X0Y0_S4BEG),
    .SS4BEG(Tile_X0Y0_SS4BEG),
    .BASE_TO_TOP(NPU_PSUM_PORT0_BASE_TO_TOP),
    .TOP_TO_BASE(NPU_PSUM_PORT0_TOP_TO_BASE),
    .UserCLK(Tile_X0Y0_UserCLK),
    .UserCLKo(Tile_X0Y0_UserCLKo),
    .FrameData(Tile_X0Y0_FrameData),
    .FrameData_O(Tile_X0Y0_FrameData_O),
    .FrameStrobe(Tile_X0Y0_FrameStrobe),
    .FrameStrobe_O(Tile_X0Y0_FrameStrobe_O)
);

NPU_PSUM_PORT1
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X1Y0_Emulate_Bitstream)
    )
`endif
    Tile_X1Y0_NPU_PSUM_PORT1
    (
    .N1END(Tile_X1Y0_N1END),
    .N2MID(Tile_X1Y0_N2MID),
    .N2END(Tile_X1Y0_N2END),
    .N4END(Tile_X1Y0_N4END),
    .NN4END(Tile_X1Y0_NN4END),
    .Ci(Tile_X1Y0_Ci),
    .S1BEG(Tile_X1Y0_S1BEG),
    .S2BEG(Tile_X1Y0_S2BEG),
    .S2BEGb(Tile_X1Y0_S2BEGb),
    .S4BEG(Tile_X1Y0_S4BEG),
    .SS4BEG(Tile_X1Y0_SS4BEG),
    .BASE_TO_TOP(NPU_PSUM_PORT1_BASE_TO_TOP),
    .TOP_TO_BASE(NPU_PSUM_PORT1_TOP_TO_BASE),
    .UserCLK(Tile_X1Y0_UserCLK),
    .UserCLKo(Tile_X1Y0_UserCLKo),
    .FrameData(Tile_X0Y0_FrameData_O),
    .FrameData_O(Tile_X1Y0_FrameData_O),
    .FrameStrobe(Tile_X1Y0_FrameStrobe),
    .FrameStrobe_O(Tile_X1Y0_FrameStrobe_O)
);

NPU_PSUM_PORT_switch_matrix Inst_NPU_PSUM_PORT_switch_matrix (
    .NPU_PSUM_PORT0_BASE_TO_TOP0(NPU_PSUM_PORT0_BASE_TO_TOP[0]),
    .NPU_PSUM_PORT0_BASE_TO_TOP1(NPU_PSUM_PORT0_BASE_TO_TOP[1]),
    .NPU_PSUM_PORT0_BASE_TO_TOP2(NPU_PSUM_PORT0_BASE_TO_TOP[2]),
    .NPU_PSUM_PORT0_BASE_TO_TOP3(NPU_PSUM_PORT0_BASE_TO_TOP[3]),
    .NPU_PSUM_PORT0_BASE_TO_TOP4(NPU_PSUM_PORT0_BASE_TO_TOP[4]),
    .NPU_PSUM_PORT0_BASE_TO_TOP5(NPU_PSUM_PORT0_BASE_TO_TOP[5]),
    .NPU_PSUM_PORT0_BASE_TO_TOP6(NPU_PSUM_PORT0_BASE_TO_TOP[6]),
    .NPU_PSUM_PORT0_BASE_TO_TOP7(NPU_PSUM_PORT0_BASE_TO_TOP[7]),
    .NPU_PSUM_PORT0_BASE_TO_TOP8(NPU_PSUM_PORT0_BASE_TO_TOP[8]),
    .NPU_PSUM_PORT0_BASE_TO_TOP9(NPU_PSUM_PORT0_BASE_TO_TOP[9]),
    .NPU_PSUM_PORT0_BASE_TO_TOP10(NPU_PSUM_PORT0_BASE_TO_TOP[10]),
    .NPU_PSUM_PORT0_BASE_TO_TOP11(NPU_PSUM_PORT0_BASE_TO_TOP[11]),
    .NPU_PSUM_PORT0_BASE_TO_TOP12(NPU_PSUM_PORT0_BASE_TO_TOP[12]),
    .NPU_PSUM_PORT0_BASE_TO_TOP13(NPU_PSUM_PORT0_BASE_TO_TOP[13]),
    .NPU_PSUM_PORT0_BASE_TO_TOP14(NPU_PSUM_PORT0_BASE_TO_TOP[14]),
    .NPU_PSUM_PORT0_BASE_TO_TOP15(NPU_PSUM_PORT0_BASE_TO_TOP[15]),
    .NPU_PSUM_PORT0_BASE_TO_TOP16(NPU_PSUM_PORT0_BASE_TO_TOP[16]),
    .NPU_PSUM_PORT0_BASE_TO_TOP17(NPU_PSUM_PORT0_BASE_TO_TOP[17]),
    .NPU_PSUM_PORT0_BASE_TO_TOP18(NPU_PSUM_PORT0_BASE_TO_TOP[18]),
    .NPU_PSUM_PORT0_BASE_TO_TOP19(NPU_PSUM_PORT0_BASE_TO_TOP[19]),
    .NPU_PSUM_PORT0_BASE_TO_TOP20(NPU_PSUM_PORT0_BASE_TO_TOP[20]),
    .NPU_PSUM_PORT0_BASE_TO_TOP21(NPU_PSUM_PORT0_BASE_TO_TOP[21]),
    .NPU_PSUM_PORT0_BASE_TO_TOP22(NPU_PSUM_PORT0_BASE_TO_TOP[22]),
    .NPU_PSUM_PORT0_BASE_TO_TOP23(NPU_PSUM_PORT0_BASE_TO_TOP[23]),
    .NPU_PSUM_PORT0_BASE_TO_TOP24(NPU_PSUM_PORT0_BASE_TO_TOP[24]),
    .NPU_PSUM_PORT0_BASE_TO_TOP25(NPU_PSUM_PORT0_BASE_TO_TOP[25]),
    .NPU_PSUM_PORT0_BASE_TO_TOP26(NPU_PSUM_PORT0_BASE_TO_TOP[26]),
    .NPU_PSUM_PORT0_BASE_TO_TOP27(NPU_PSUM_PORT0_BASE_TO_TOP[27]),
    .NPU_PSUM_PORT0_BASE_TO_TOP28(NPU_PSUM_PORT0_BASE_TO_TOP[28]),
    .NPU_PSUM_PORT0_BASE_TO_TOP29(NPU_PSUM_PORT0_BASE_TO_TOP[29]),
    .NPU_PSUM_PORT0_BASE_TO_TOP30(NPU_PSUM_PORT0_BASE_TO_TOP[30]),
    .NPU_PSUM_PORT0_BASE_TO_TOP31(NPU_PSUM_PORT0_BASE_TO_TOP[31]),
    .NPU_PSUM_PORT1_BASE_TO_TOP0(NPU_PSUM_PORT1_BASE_TO_TOP[0]),
    .NPU_PSUM_PORT1_BASE_TO_TOP1(NPU_PSUM_PORT1_BASE_TO_TOP[1]),
    .NPU_PSUM_PORT1_BASE_TO_TOP2(NPU_PSUM_PORT1_BASE_TO_TOP[2]),
    .NPU_PSUM_PORT1_BASE_TO_TOP3(NPU_PSUM_PORT1_BASE_TO_TOP[3]),
    .NPU_PSUM_PORT1_BASE_TO_TOP4(NPU_PSUM_PORT1_BASE_TO_TOP[4]),
    .NPU_PSUM_PORT1_BASE_TO_TOP5(NPU_PSUM_PORT1_BASE_TO_TOP[5]),
    .NPU_PSUM_PORT1_BASE_TO_TOP6(NPU_PSUM_PORT1_BASE_TO_TOP[6]),
    .NPU_PSUM_PORT1_BASE_TO_TOP7(NPU_PSUM_PORT1_BASE_TO_TOP[7]),
    .NPU_PSUM_PORT1_BASE_TO_TOP8(NPU_PSUM_PORT1_BASE_TO_TOP[8]),
    .NPU_PSUM_PORT1_BASE_TO_TOP9(NPU_PSUM_PORT1_BASE_TO_TOP[9]),
    .NPU_PSUM_PORT1_BASE_TO_TOP10(NPU_PSUM_PORT1_BASE_TO_TOP[10]),
    .NPU_PSUM_PORT1_BASE_TO_TOP11(NPU_PSUM_PORT1_BASE_TO_TOP[11]),
    .NPU_PSUM_PORT1_BASE_TO_TOP12(NPU_PSUM_PORT1_BASE_TO_TOP[12]),
    .NPU_PSUM_PORT1_BASE_TO_TOP13(NPU_PSUM_PORT1_BASE_TO_TOP[13]),
    .NPU_PSUM_PORT1_BASE_TO_TOP14(NPU_PSUM_PORT1_BASE_TO_TOP[14]),
    .NPU_PSUM_PORT1_BASE_TO_TOP15(NPU_PSUM_PORT1_BASE_TO_TOP[15]),
    .NPU_PSUM_PORT1_BASE_TO_TOP16(NPU_PSUM_PORT1_BASE_TO_TOP[16]),
    .NPU_PSUM_PORT1_BASE_TO_TOP17(NPU_PSUM_PORT1_BASE_TO_TOP[17]),
    .NPU_PSUM_PORT1_BASE_TO_TOP18(NPU_PSUM_PORT1_BASE_TO_TOP[18]),
    .FAB_ADDR0(FAB_ADDR0),
    .FAB_ADDR1(FAB_ADDR1),
    .FAB_ADDR2(FAB_ADDR2),
    .FAB_ADDR3(FAB_ADDR3),
    .FAB_ADDR4(FAB_ADDR4),
    .FAB_ADDR5(FAB_ADDR5),
    .FAB_ADDR6(FAB_ADDR6),
    .FAB_ADDR7(FAB_ADDR7),
    .FAB_WE0(FAB_WE0),
    .FAB_WE1(FAB_WE1),
    .FAB_WE2(FAB_WE2),
    .FAB_WE3(FAB_WE3),
    .FAB_WE4(FAB_WE4),
    .FAB_WE5(FAB_WE5),
    .FAB_WE6(FAB_WE6),
    .FAB_WE7(FAB_WE7),
    .FAB_WDATA0(FAB_WDATA0),
    .FAB_WDATA1(FAB_WDATA1),
    .FAB_WDATA2(FAB_WDATA2),
    .FAB_WDATA3(FAB_WDATA3),
    .FAB_WDATA4(FAB_WDATA4),
    .FAB_WDATA5(FAB_WDATA5),
    .FAB_WDATA6(FAB_WDATA6),
    .FAB_WDATA7(FAB_WDATA7),
    .FAB_WDATA8(FAB_WDATA8),
    .FAB_WDATA9(FAB_WDATA9),
    .FAB_WDATA10(FAB_WDATA10),
    .FAB_WDATA11(FAB_WDATA11),
    .FAB_WDATA12(FAB_WDATA12),
    .FAB_WDATA13(FAB_WDATA13),
    .FAB_WDATA14(FAB_WDATA14),
    .FAB_WDATA15(FAB_WDATA15),
    .FAB_WDATA16(FAB_WDATA16),
    .FAB_WDATA17(FAB_WDATA17),
    .FAB_WDATA18(FAB_WDATA18),
    .FAB_WDATA19(FAB_WDATA19),
    .FAB_WDATA20(FAB_WDATA20),
    .FAB_WDATA21(FAB_WDATA21),
    .FAB_WDATA22(FAB_WDATA22),
    .FAB_WDATA23(FAB_WDATA23),
    .FAB_WDATA24(FAB_WDATA24),
    .FAB_WDATA25(FAB_WDATA25),
    .FAB_WDATA26(FAB_WDATA26),
    .FAB_WDATA27(FAB_WDATA27),
    .FAB_WDATA28(FAB_WDATA28),
    .FAB_WDATA29(FAB_WDATA29),
    .FAB_WDATA30(FAB_WDATA30),
    .FAB_WDATA31(FAB_WDATA31),
    .FAB_READ_BANK_SEL0(FAB_READ_BANK_SEL0),
    .FAB_READ_BANK_SEL1(FAB_READ_BANK_SEL1),
    .FAB_READ_BANK_SEL2(FAB_READ_BANK_SEL2),
    .FAB_RDATA0(FAB_RDATA0),
    .FAB_RDATA1(FAB_RDATA1),
    .FAB_RDATA2(FAB_RDATA2),
    .FAB_RDATA3(FAB_RDATA3),
    .FAB_RDATA4(FAB_RDATA4),
    .FAB_RDATA5(FAB_RDATA5),
    .FAB_RDATA6(FAB_RDATA6),
    .FAB_RDATA7(FAB_RDATA7),
    .FAB_RDATA8(FAB_RDATA8),
    .FAB_RDATA9(FAB_RDATA9),
    .FAB_RDATA10(FAB_RDATA10),
    .FAB_RDATA11(FAB_RDATA11),
    .FAB_RDATA12(FAB_RDATA12),
    .FAB_RDATA13(FAB_RDATA13),
    .FAB_RDATA14(FAB_RDATA14),
    .FAB_RDATA15(FAB_RDATA15),
    .FAB_RDATA16(FAB_RDATA16),
    .FAB_RDATA17(FAB_RDATA17),
    .FAB_RDATA18(FAB_RDATA18),
    .FAB_RDATA19(FAB_RDATA19),
    .FAB_RDATA20(FAB_RDATA20),
    .FAB_RDATA21(FAB_RDATA21),
    .FAB_RDATA22(FAB_RDATA22),
    .FAB_RDATA23(FAB_RDATA23),
    .FAB_RDATA24(FAB_RDATA24),
    .FAB_RDATA25(FAB_RDATA25),
    .FAB_RDATA26(FAB_RDATA26),
    .FAB_RDATA27(FAB_RDATA27),
    .FAB_RDATA28(FAB_RDATA28),
    .FAB_RDATA29(FAB_RDATA29),
    .FAB_RDATA30(FAB_RDATA30),
    .FAB_RDATA31(FAB_RDATA31),
    .NPU_PSUM_PORT0_TOP_TO_BASE0(NPU_PSUM_PORT0_TOP_TO_BASE[0]),
    .NPU_PSUM_PORT0_TOP_TO_BASE1(NPU_PSUM_PORT0_TOP_TO_BASE[1]),
    .NPU_PSUM_PORT0_TOP_TO_BASE2(NPU_PSUM_PORT0_TOP_TO_BASE[2]),
    .NPU_PSUM_PORT0_TOP_TO_BASE3(NPU_PSUM_PORT0_TOP_TO_BASE[3]),
    .NPU_PSUM_PORT0_TOP_TO_BASE4(NPU_PSUM_PORT0_TOP_TO_BASE[4]),
    .NPU_PSUM_PORT0_TOP_TO_BASE5(NPU_PSUM_PORT0_TOP_TO_BASE[5]),
    .NPU_PSUM_PORT0_TOP_TO_BASE6(NPU_PSUM_PORT0_TOP_TO_BASE[6]),
    .NPU_PSUM_PORT0_TOP_TO_BASE7(NPU_PSUM_PORT0_TOP_TO_BASE[7]),
    .NPU_PSUM_PORT0_TOP_TO_BASE8(NPU_PSUM_PORT0_TOP_TO_BASE[8]),
    .NPU_PSUM_PORT0_TOP_TO_BASE9(NPU_PSUM_PORT0_TOP_TO_BASE[9]),
    .NPU_PSUM_PORT0_TOP_TO_BASE10(NPU_PSUM_PORT0_TOP_TO_BASE[10]),
    .NPU_PSUM_PORT0_TOP_TO_BASE11(NPU_PSUM_PORT0_TOP_TO_BASE[11]),
    .NPU_PSUM_PORT0_TOP_TO_BASE12(NPU_PSUM_PORT0_TOP_TO_BASE[12]),
    .NPU_PSUM_PORT0_TOP_TO_BASE13(NPU_PSUM_PORT0_TOP_TO_BASE[13]),
    .NPU_PSUM_PORT0_TOP_TO_BASE14(NPU_PSUM_PORT0_TOP_TO_BASE[14]),
    .NPU_PSUM_PORT0_TOP_TO_BASE15(NPU_PSUM_PORT0_TOP_TO_BASE[15]),
    .NPU_PSUM_PORT1_TOP_TO_BASE0(NPU_PSUM_PORT1_TOP_TO_BASE[0]),
    .NPU_PSUM_PORT1_TOP_TO_BASE1(NPU_PSUM_PORT1_TOP_TO_BASE[1]),
    .NPU_PSUM_PORT1_TOP_TO_BASE2(NPU_PSUM_PORT1_TOP_TO_BASE[2]),
    .NPU_PSUM_PORT1_TOP_TO_BASE3(NPU_PSUM_PORT1_TOP_TO_BASE[3]),
    .NPU_PSUM_PORT1_TOP_TO_BASE4(NPU_PSUM_PORT1_TOP_TO_BASE[4]),
    .NPU_PSUM_PORT1_TOP_TO_BASE5(NPU_PSUM_PORT1_TOP_TO_BASE[5]),
    .NPU_PSUM_PORT1_TOP_TO_BASE6(NPU_PSUM_PORT1_TOP_TO_BASE[6]),
    .NPU_PSUM_PORT1_TOP_TO_BASE7(NPU_PSUM_PORT1_TOP_TO_BASE[7]),
    .NPU_PSUM_PORT1_TOP_TO_BASE8(NPU_PSUM_PORT1_TOP_TO_BASE[8]),
    .NPU_PSUM_PORT1_TOP_TO_BASE9(NPU_PSUM_PORT1_TOP_TO_BASE[9]),
    .NPU_PSUM_PORT1_TOP_TO_BASE10(NPU_PSUM_PORT1_TOP_TO_BASE[10]),
    .NPU_PSUM_PORT1_TOP_TO_BASE11(NPU_PSUM_PORT1_TOP_TO_BASE[11]),
    .NPU_PSUM_PORT1_TOP_TO_BASE12(NPU_PSUM_PORT1_TOP_TO_BASE[12]),
    .NPU_PSUM_PORT1_TOP_TO_BASE13(NPU_PSUM_PORT1_TOP_TO_BASE[13]),
    .NPU_PSUM_PORT1_TOP_TO_BASE14(NPU_PSUM_PORT1_TOP_TO_BASE[14]),
    .NPU_PSUM_PORT1_TOP_TO_BASE15(NPU_PSUM_PORT1_TOP_TO_BASE[15])
);

NPU_PSUM_PORT_BEL Inst_ST_NPU_PSUM_PORT_BEL (
    .FAB_ADDR({FAB_ADDR7, FAB_ADDR6, FAB_ADDR5, FAB_ADDR4, FAB_ADDR3, FAB_ADDR2, FAB_ADDR1, FAB_ADDR0}),
    .FAB_WE({FAB_WE7, FAB_WE6, FAB_WE5, FAB_WE4, FAB_WE3, FAB_WE2, FAB_WE1, FAB_WE0}),
    .FAB_WDATA({FAB_WDATA31, FAB_WDATA30, FAB_WDATA29, FAB_WDATA28, FAB_WDATA27, FAB_WDATA26, FAB_WDATA25, FAB_WDATA24, FAB_WDATA23, FAB_WDATA22, FAB_WDATA21, FAB_WDATA20, FAB_WDATA19, FAB_WDATA18, FAB_WDATA17, FAB_WDATA16, FAB_WDATA15, FAB_WDATA14, FAB_WDATA13, FAB_WDATA12, FAB_WDATA11, FAB_WDATA10, FAB_WDATA9, FAB_WDATA8, FAB_WDATA7, FAB_WDATA6, FAB_WDATA5, FAB_WDATA4, FAB_WDATA3, FAB_WDATA2, FAB_WDATA1, FAB_WDATA0}),
    .FAB_READ_BANK_SEL({FAB_READ_BANK_SEL2, FAB_READ_BANK_SEL1, FAB_READ_BANK_SEL0}),
    .FAB_RDATA({FAB_RDATA31, FAB_RDATA30, FAB_RDATA29, FAB_RDATA28, FAB_RDATA27, FAB_RDATA26, FAB_RDATA25, FAB_RDATA24, FAB_RDATA23, FAB_RDATA22, FAB_RDATA21, FAB_RDATA20, FAB_RDATA19, FAB_RDATA18, FAB_RDATA17, FAB_RDATA16, FAB_RDATA15, FAB_RDATA14, FAB_RDATA13, FAB_RDATA12, FAB_RDATA11, FAB_RDATA10, FAB_RDATA9, FAB_RDATA8, FAB_RDATA7, FAB_RDATA6, FAB_RDATA5, FAB_RDATA4, FAB_RDATA3, FAB_RDATA2, FAB_RDATA1, FAB_RDATA0}),
    .NPU_ADDR({NPU_ADDR7, NPU_ADDR6, NPU_ADDR5, NPU_ADDR4, NPU_ADDR3, NPU_ADDR2, NPU_ADDR1, NPU_ADDR0}),
    .NPU_WE({NPU_WE7, NPU_WE6, NPU_WE5, NPU_WE4, NPU_WE3, NPU_WE2, NPU_WE1, NPU_WE0}),
    .NPU_WDATA({NPU_WDATA31, NPU_WDATA30, NPU_WDATA29, NPU_WDATA28, NPU_WDATA27, NPU_WDATA26, NPU_WDATA25, NPU_WDATA24, NPU_WDATA23, NPU_WDATA22, NPU_WDATA21, NPU_WDATA20, NPU_WDATA19, NPU_WDATA18, NPU_WDATA17, NPU_WDATA16, NPU_WDATA15, NPU_WDATA14, NPU_WDATA13, NPU_WDATA12, NPU_WDATA11, NPU_WDATA10, NPU_WDATA9, NPU_WDATA8, NPU_WDATA7, NPU_WDATA6, NPU_WDATA5, NPU_WDATA4, NPU_WDATA3, NPU_WDATA2, NPU_WDATA1, NPU_WDATA0}),
    .NPU_READ_BANK_SEL({NPU_READ_BANK_SEL2, NPU_READ_BANK_SEL1, NPU_READ_BANK_SEL0}),
    .NPU_RDATA({NPU_RDATA31, NPU_RDATA30, NPU_RDATA29, NPU_RDATA28, NPU_RDATA27, NPU_RDATA26, NPU_RDATA25, NPU_RDATA24, NPU_RDATA23, NPU_RDATA22, NPU_RDATA21, NPU_RDATA20, NPU_RDATA19, NPU_RDATA18, NPU_RDATA17, NPU_RDATA16, NPU_RDATA15, NPU_RDATA14, NPU_RDATA13, NPU_RDATA12, NPU_RDATA11, NPU_RDATA10, NPU_RDATA9, NPU_RDATA8, NPU_RDATA7, NPU_RDATA6, NPU_RDATA5, NPU_RDATA4, NPU_RDATA3, NPU_RDATA2, NPU_RDATA1, NPU_RDATA0})
);

endmodule