# =============================================================================
# CrocoScale SoC — Standalone IP Export: npu
# Auto-generated by scripts/export_subsystem.py
# Format: v | Zero external library dependencies
# =============================================================================

RTL/sram_bank.v
RTL/npu_prng_16bit.v
RTL/npu_requantizer_lane.v
RTL/npu_requantizer.v
RTL/pe.v
RTL/npu_crossbar.v
RTL/systolic_array.v
RTL/npu_top.v
RTL/npu_wrapper.v
