module NPU_CTRL_CFG
    #(
`ifdef EMULATION
        parameter [639:0] Tile_X0Y0_Emulate_Bitstream=640'b0,
        parameter [639:0] Tile_X1Y0_Emulate_Bitstream=640'b0,
`endif
        parameter MaxFramesPerCol=20,
        parameter FrameBitsPerRow=32
    )
    (
    //Tile_X0Y0_Direction.NORTH
        input  [3:0] Tile_X0Y0_N1END, //TilePort({S} INPUT N1END[3:0])
        input  [7:0] Tile_X0Y0_N2MID, //TilePort({S} INPUT N2MID[7:0])
        input  [7:0] Tile_X0Y0_N2END, //TilePort({S} INPUT N2END[7:0])
        input  [15:0] Tile_X0Y0_N4END, //TilePort({S} INPUT N4END[3:0])
        input  [15:0] Tile_X0Y0_NN4END, //TilePort({S} INPUT NN4END[3:0])
        input  [0:0] Tile_X0Y0_Ci, //TilePort({S} INPUT Ci[0:0])
        output  [3:0] Tile_X0Y0_S1BEG, //TilePort({S} OUTPUT S1BEG[3:0])
        output  [7:0] Tile_X0Y0_S2BEG, //TilePort({S} OUTPUT S2BEG[7:0])
        output  [7:0] Tile_X0Y0_S2BEGb, //TilePort({S} OUTPUT S2BEGb[7:0])
        output  [15:0] Tile_X0Y0_S4BEG, //TilePort({S} OUTPUT S4BEG[3:0])
        output  [15:0] Tile_X0Y0_SS4BEG, //TilePort({S} OUTPUT SS4BEG[3:0])
    //Tile_X1Y0_Direction.NORTH
        input  [3:0] Tile_X1Y0_N1END, //TilePort({S} INPUT N1END[3:0])
        input  [7:0] Tile_X1Y0_N2MID, //TilePort({S} INPUT N2MID[7:0])
        input  [7:0] Tile_X1Y0_N2END, //TilePort({S} INPUT N2END[7:0])
        input  [15:0] Tile_X1Y0_N4END, //TilePort({S} INPUT N4END[3:0])
        input  [15:0] Tile_X1Y0_NN4END, //TilePort({S} INPUT NN4END[3:0])
        input  [0:0] Tile_X1Y0_Ci, //TilePort({S} INPUT Ci[0:0])
        output  [3:0] Tile_X1Y0_S1BEG, //TilePort({S} OUTPUT S1BEG[3:0])
        output  [7:0] Tile_X1Y0_S2BEG, //TilePort({S} OUTPUT S2BEG[7:0])
        output  [7:0] Tile_X1Y0_S2BEGb, //TilePort({S} OUTPUT S2BEGb[7:0])
        output  [15:0] Tile_X1Y0_S4BEG, //TilePort({S} OUTPUT S4BEG[3:0])
        output  [15:0] Tile_X1Y0_SS4BEG, //TilePort({S} OUTPUT SS4BEG[3:0])
    //Tile IO ports from BELs
    //SuperTile BEL IO ports
        output  NPU_QUANT_SHIFT_IN0,
        output  NPU_QUANT_SHIFT_IN1,
        output  NPU_QUANT_SHIFT_IN2,
        output  NPU_QUANT_SHIFT_IN3,
        output  NPU_QUANT_SHIFT_IN4,
        output  NPU_QUANT_SHIFT_IN5,
        output  NPU_QUANT_SHIFT_IN6,
        output  NPU_QUANT_SHIFT_IN7,
        output  NPU_QUANT_SHIFT_IN8,
        output  NPU_QUANT_SHIFT_IN9,
        output  NPU_QUANT_SHIFT_IN10,
        output  NPU_QUANT_SHIFT_IN11,
        output  NPU_QUANT_SHIFT_IN12,
        output  NPU_QUANT_SHIFT_IN13,
        output  NPU_QUANT_SHIFT_IN14,
        output  NPU_QUANT_SHIFT_IN15,
        output  NPU_QUANT_SHIFT_IN16,
        output  NPU_QUANT_SHIFT_IN17,
        output  NPU_QUANT_SHIFT_IN18,
        output  NPU_QUANT_SHIFT_IN19,
        output  NPU_QUANT_SHIFT_IN20,
        output  NPU_QUANT_SHIFT_IN21,
        output  NPU_QUANT_SHIFT_IN22,
        output  NPU_QUANT_SHIFT_IN23,
        output  NPU_QUANT_SHIFT_IN24,
        output  NPU_QUANT_SHIFT_IN25,
        output  NPU_QUANT_SHIFT_IN26,
        output  NPU_QUANT_SHIFT_IN27,
        output  NPU_QUANT_SHIFT_IN28,
        output  NPU_QUANT_SHIFT_IN29,
        output  NPU_QUANT_SHIFT_EN,
        output  NPU_ARRAY_EN,
        output  NPU_PSUM_SYSTOLIC_EN,
        output  NPU_PSUM_LUT_EN,
        output  NPU_SWAP_WEIGHTS,
        output  NPU_PSUM_SKEW_EN,
        output  NPU_COMPUTE_BANK_SWAP,
        output  [MaxFramesPerCol-1:0] Tile_X0Y0_FrameStrobe_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y0_FrameData, //CONFIG_PORT
        input  [MaxFramesPerCol-1:0] Tile_X0Y0_FrameStrobe, //CONFIG_PORT
        output  [MaxFramesPerCol-1:0] Tile_X1Y0_FrameStrobe_O, //CONFIG_PORT
        input  [MaxFramesPerCol-1:0] Tile_X1Y0_FrameStrobe, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X1Y0_FrameData_O, //CONFIG_PORT
        input  Tile_X0Y0_UserCLK,
        output  Tile_X1Y0_UserCLKo
);

 //signal declarations
 //SJUMP signals (child tile -> supertile SM)
    wire[18-1:0] NPU_CTRL_CFG_0_BASE_TO_TOP;
    wire[19-1:0] NPU_CTRL_CFG_1_BASE_TO_TOP;
 //BEL pin signals (BEL <-> supertile SM)
    wire FAB_QUANT_SHIFT_IN0;
    wire FAB_QUANT_SHIFT_IN1;
    wire FAB_QUANT_SHIFT_IN2;
    wire FAB_QUANT_SHIFT_IN3;
    wire FAB_QUANT_SHIFT_IN4;
    wire FAB_QUANT_SHIFT_IN5;
    wire FAB_QUANT_SHIFT_IN6;
    wire FAB_QUANT_SHIFT_IN7;
    wire FAB_QUANT_SHIFT_IN8;
    wire FAB_QUANT_SHIFT_IN9;
    wire FAB_QUANT_SHIFT_IN10;
    wire FAB_QUANT_SHIFT_IN11;
    wire FAB_QUANT_SHIFT_IN12;
    wire FAB_QUANT_SHIFT_IN13;
    wire FAB_QUANT_SHIFT_IN14;
    wire FAB_QUANT_SHIFT_IN15;
    wire FAB_QUANT_SHIFT_IN16;
    wire FAB_QUANT_SHIFT_IN17;
    wire FAB_QUANT_SHIFT_IN18;
    wire FAB_QUANT_SHIFT_IN19;
    wire FAB_QUANT_SHIFT_IN20;
    wire FAB_QUANT_SHIFT_IN21;
    wire FAB_QUANT_SHIFT_IN22;
    wire FAB_QUANT_SHIFT_IN23;
    wire FAB_QUANT_SHIFT_IN24;
    wire FAB_QUANT_SHIFT_IN25;
    wire FAB_QUANT_SHIFT_IN26;
    wire FAB_QUANT_SHIFT_IN27;
    wire FAB_QUANT_SHIFT_IN28;
    wire FAB_QUANT_SHIFT_IN29;
    wire FAB_QUANT_SHIFT_EN;
    wire FAB_ARRAY_EN;
    wire FAB_PSUM_SYSTOLIC_EN;
    wire FAB_PSUM_LUT_EN;
    wire FAB_SWAP_WEIGHTS;
    wire FAB_PSUM_SKEW_EN;
    wire FAB_COMPUTE_BANK_SWAP;
    wire Tile_X0Y0_UserCLKo;
    wire[FrameBitsPerRow-1:0] Tile_X0Y0_FrameData_O;
    wire[1-1:0] ST_ConfigBits;
    wire[1-1:0] ST_ConfigBits_N;

NPU_CTRL_CFG_0
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y0_Emulate_Bitstream)
    )
`endif
    Tile_X0Y0_NPU_CTRL_CFG_0
    (
    .N1END(Tile_X0Y0_N1END),
    .N2MID(Tile_X0Y0_N2MID),
    .N2END(Tile_X0Y0_N2END),
    .N4END(Tile_X0Y0_N4END),
    .NN4END(Tile_X0Y0_NN4END),
    .Ci(Tile_X0Y0_Ci),
    .S1BEG(Tile_X0Y0_S1BEG),
    .S2BEG(Tile_X0Y0_S2BEG),
    .S2BEGb(Tile_X0Y0_S2BEGb),
    .S4BEG(Tile_X0Y0_S4BEG),
    .SS4BEG(Tile_X0Y0_SS4BEG),
    .BASE_TO_TOP(NPU_CTRL_CFG_0_BASE_TO_TOP),
    .UserCLK(Tile_X0Y0_UserCLK),
    .UserCLKo(Tile_X0Y0_UserCLKo),
    .FrameData(Tile_X0Y0_FrameData),
    .FrameData_O(Tile_X0Y0_FrameData_O),
    .FrameStrobe(Tile_X0Y0_FrameStrobe),
    .FrameStrobe_O(Tile_X0Y0_FrameStrobe_O)
);

NPU_CTRL_CFG_1
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X1Y0_Emulate_Bitstream)
    )
`endif
    Tile_X1Y0_NPU_CTRL_CFG_1
    (
    .N1END(Tile_X1Y0_N1END),
    .N2MID(Tile_X1Y0_N2MID),
    .N2END(Tile_X1Y0_N2END),
    .N4END(Tile_X1Y0_N4END),
    .NN4END(Tile_X1Y0_NN4END),
    .Ci(Tile_X1Y0_Ci),
    .S1BEG(Tile_X1Y0_S1BEG),
    .S2BEG(Tile_X1Y0_S2BEG),
    .S2BEGb(Tile_X1Y0_S2BEGb),
    .S4BEG(Tile_X1Y0_S4BEG),
    .SS4BEG(Tile_X1Y0_SS4BEG),
    .BASE_TO_TOP(NPU_CTRL_CFG_1_BASE_TO_TOP),
    .UserCLK(Tile_X0Y0_UserCLKo),
    .UserCLKo(Tile_X1Y0_UserCLKo),
    .FrameData(Tile_X0Y0_FrameData_O),
    .FrameData_O(Tile_X1Y0_FrameData_O),
    .FrameStrobe(Tile_X1Y0_FrameStrobe),
    .FrameStrobe_O(Tile_X1Y0_FrameStrobe_O)
);

NPU_CTRL_CFG_ConfigMem
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X1Y0_Emulate_Bitstream)
    )
`endif
    Inst_NPU_CTRL_CFG_ConfigMem
    (
    .FrameData(Tile_X0Y0_FrameData_O),
    .FrameStrobe(Tile_X1Y0_FrameStrobe),
    .ConfigBits(ST_ConfigBits[1-1:0]),
    .ConfigBits_N(ST_ConfigBits_N[1-1:0])
);

NPU_CTRL_CFG_switch_matrix Inst_NPU_CTRL_CFG_switch_matrix (
    .NPU_CTRL_CFG_0_BASE_TO_TOP0(NPU_CTRL_CFG_0_BASE_TO_TOP[0]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP1(NPU_CTRL_CFG_0_BASE_TO_TOP[1]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP2(NPU_CTRL_CFG_0_BASE_TO_TOP[2]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP3(NPU_CTRL_CFG_0_BASE_TO_TOP[3]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP4(NPU_CTRL_CFG_0_BASE_TO_TOP[4]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP5(NPU_CTRL_CFG_0_BASE_TO_TOP[5]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP6(NPU_CTRL_CFG_0_BASE_TO_TOP[6]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP7(NPU_CTRL_CFG_0_BASE_TO_TOP[7]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP8(NPU_CTRL_CFG_0_BASE_TO_TOP[8]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP9(NPU_CTRL_CFG_0_BASE_TO_TOP[9]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP10(NPU_CTRL_CFG_0_BASE_TO_TOP[10]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP11(NPU_CTRL_CFG_0_BASE_TO_TOP[11]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP12(NPU_CTRL_CFG_0_BASE_TO_TOP[12]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP13(NPU_CTRL_CFG_0_BASE_TO_TOP[13]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP14(NPU_CTRL_CFG_0_BASE_TO_TOP[14]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP15(NPU_CTRL_CFG_0_BASE_TO_TOP[15]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP16(NPU_CTRL_CFG_0_BASE_TO_TOP[16]),
    .NPU_CTRL_CFG_0_BASE_TO_TOP17(NPU_CTRL_CFG_0_BASE_TO_TOP[17]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP0(NPU_CTRL_CFG_1_BASE_TO_TOP[0]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP1(NPU_CTRL_CFG_1_BASE_TO_TOP[1]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP2(NPU_CTRL_CFG_1_BASE_TO_TOP[2]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP3(NPU_CTRL_CFG_1_BASE_TO_TOP[3]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP4(NPU_CTRL_CFG_1_BASE_TO_TOP[4]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP5(NPU_CTRL_CFG_1_BASE_TO_TOP[5]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP6(NPU_CTRL_CFG_1_BASE_TO_TOP[6]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP7(NPU_CTRL_CFG_1_BASE_TO_TOP[7]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP8(NPU_CTRL_CFG_1_BASE_TO_TOP[8]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP9(NPU_CTRL_CFG_1_BASE_TO_TOP[9]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP10(NPU_CTRL_CFG_1_BASE_TO_TOP[10]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP11(NPU_CTRL_CFG_1_BASE_TO_TOP[11]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP12(NPU_CTRL_CFG_1_BASE_TO_TOP[12]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP13(NPU_CTRL_CFG_1_BASE_TO_TOP[13]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP14(NPU_CTRL_CFG_1_BASE_TO_TOP[14]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP15(NPU_CTRL_CFG_1_BASE_TO_TOP[15]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP16(NPU_CTRL_CFG_1_BASE_TO_TOP[16]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP17(NPU_CTRL_CFG_1_BASE_TO_TOP[17]),
    .NPU_CTRL_CFG_1_BASE_TO_TOP18(NPU_CTRL_CFG_1_BASE_TO_TOP[18]),
    .FAB_QUANT_SHIFT_IN0(FAB_QUANT_SHIFT_IN0),
    .FAB_QUANT_SHIFT_IN1(FAB_QUANT_SHIFT_IN1),
    .FAB_QUANT_SHIFT_IN2(FAB_QUANT_SHIFT_IN2),
    .FAB_QUANT_SHIFT_IN3(FAB_QUANT_SHIFT_IN3),
    .FAB_QUANT_SHIFT_IN4(FAB_QUANT_SHIFT_IN4),
    .FAB_QUANT_SHIFT_IN5(FAB_QUANT_SHIFT_IN5),
    .FAB_QUANT_SHIFT_IN6(FAB_QUANT_SHIFT_IN6),
    .FAB_QUANT_SHIFT_IN7(FAB_QUANT_SHIFT_IN7),
    .FAB_QUANT_SHIFT_IN8(FAB_QUANT_SHIFT_IN8),
    .FAB_QUANT_SHIFT_IN9(FAB_QUANT_SHIFT_IN9),
    .FAB_QUANT_SHIFT_IN10(FAB_QUANT_SHIFT_IN10),
    .FAB_QUANT_SHIFT_IN11(FAB_QUANT_SHIFT_IN11),
    .FAB_QUANT_SHIFT_IN12(FAB_QUANT_SHIFT_IN12),
    .FAB_QUANT_SHIFT_IN13(FAB_QUANT_SHIFT_IN13),
    .FAB_QUANT_SHIFT_IN14(FAB_QUANT_SHIFT_IN14),
    .FAB_QUANT_SHIFT_IN15(FAB_QUANT_SHIFT_IN15),
    .FAB_QUANT_SHIFT_IN16(FAB_QUANT_SHIFT_IN16),
    .FAB_QUANT_SHIFT_IN17(FAB_QUANT_SHIFT_IN17),
    .FAB_QUANT_SHIFT_IN18(FAB_QUANT_SHIFT_IN18),
    .FAB_QUANT_SHIFT_IN19(FAB_QUANT_SHIFT_IN19),
    .FAB_QUANT_SHIFT_IN20(FAB_QUANT_SHIFT_IN20),
    .FAB_QUANT_SHIFT_IN21(FAB_QUANT_SHIFT_IN21),
    .FAB_QUANT_SHIFT_IN22(FAB_QUANT_SHIFT_IN22),
    .FAB_QUANT_SHIFT_IN23(FAB_QUANT_SHIFT_IN23),
    .FAB_QUANT_SHIFT_IN24(FAB_QUANT_SHIFT_IN24),
    .FAB_QUANT_SHIFT_IN25(FAB_QUANT_SHIFT_IN25),
    .FAB_QUANT_SHIFT_IN26(FAB_QUANT_SHIFT_IN26),
    .FAB_QUANT_SHIFT_IN27(FAB_QUANT_SHIFT_IN27),
    .FAB_QUANT_SHIFT_IN28(FAB_QUANT_SHIFT_IN28),
    .FAB_QUANT_SHIFT_IN29(FAB_QUANT_SHIFT_IN29),
    .FAB_QUANT_SHIFT_EN(FAB_QUANT_SHIFT_EN),
    .FAB_ARRAY_EN(FAB_ARRAY_EN),
    .FAB_PSUM_SYSTOLIC_EN(FAB_PSUM_SYSTOLIC_EN),
    .FAB_PSUM_LUT_EN(FAB_PSUM_LUT_EN),
    .FAB_SWAP_WEIGHTS(FAB_SWAP_WEIGHTS),
    .FAB_PSUM_SKEW_EN(FAB_PSUM_SKEW_EN),
    .FAB_COMPUTE_BANK_SWAP(FAB_COMPUTE_BANK_SWAP)
);

NPU_CTRL_CFG_BEL Inst_ST_NPU_CTRL_CFG_BEL (
    .FAB_QUANT_SHIFT_IN({FAB_QUANT_SHIFT_IN29, FAB_QUANT_SHIFT_IN28, FAB_QUANT_SHIFT_IN27, FAB_QUANT_SHIFT_IN26, FAB_QUANT_SHIFT_IN25, FAB_QUANT_SHIFT_IN24, FAB_QUANT_SHIFT_IN23, FAB_QUANT_SHIFT_IN22, FAB_QUANT_SHIFT_IN21, FAB_QUANT_SHIFT_IN20, FAB_QUANT_SHIFT_IN19, FAB_QUANT_SHIFT_IN18, FAB_QUANT_SHIFT_IN17, FAB_QUANT_SHIFT_IN16, FAB_QUANT_SHIFT_IN15, FAB_QUANT_SHIFT_IN14, FAB_QUANT_SHIFT_IN13, FAB_QUANT_SHIFT_IN12, FAB_QUANT_SHIFT_IN11, FAB_QUANT_SHIFT_IN10, FAB_QUANT_SHIFT_IN9, FAB_QUANT_SHIFT_IN8, FAB_QUANT_SHIFT_IN7, FAB_QUANT_SHIFT_IN6, FAB_QUANT_SHIFT_IN5, FAB_QUANT_SHIFT_IN4, FAB_QUANT_SHIFT_IN3, FAB_QUANT_SHIFT_IN2, FAB_QUANT_SHIFT_IN1, FAB_QUANT_SHIFT_IN0}),
    .FAB_QUANT_SHIFT_EN(FAB_QUANT_SHIFT_EN),
    .FAB_ARRAY_EN(FAB_ARRAY_EN),
    .FAB_PSUM_SYSTOLIC_EN(FAB_PSUM_SYSTOLIC_EN),
    .FAB_PSUM_LUT_EN(FAB_PSUM_LUT_EN),
    .FAB_SWAP_WEIGHTS(FAB_SWAP_WEIGHTS),
    .FAB_PSUM_SKEW_EN(FAB_PSUM_SKEW_EN),
    .FAB_COMPUTE_BANK_SWAP(FAB_COMPUTE_BANK_SWAP),
    .NPU_QUANT_SHIFT_IN({NPU_QUANT_SHIFT_IN29, NPU_QUANT_SHIFT_IN28, NPU_QUANT_SHIFT_IN27, NPU_QUANT_SHIFT_IN26, NPU_QUANT_SHIFT_IN25, NPU_QUANT_SHIFT_IN24, NPU_QUANT_SHIFT_IN23, NPU_QUANT_SHIFT_IN22, NPU_QUANT_SHIFT_IN21, NPU_QUANT_SHIFT_IN20, NPU_QUANT_SHIFT_IN19, NPU_QUANT_SHIFT_IN18, NPU_QUANT_SHIFT_IN17, NPU_QUANT_SHIFT_IN16, NPU_QUANT_SHIFT_IN15, NPU_QUANT_SHIFT_IN14, NPU_QUANT_SHIFT_IN13, NPU_QUANT_SHIFT_IN12, NPU_QUANT_SHIFT_IN11, NPU_QUANT_SHIFT_IN10, NPU_QUANT_SHIFT_IN9, NPU_QUANT_SHIFT_IN8, NPU_QUANT_SHIFT_IN7, NPU_QUANT_SHIFT_IN6, NPU_QUANT_SHIFT_IN5, NPU_QUANT_SHIFT_IN4, NPU_QUANT_SHIFT_IN3, NPU_QUANT_SHIFT_IN2, NPU_QUANT_SHIFT_IN1, NPU_QUANT_SHIFT_IN0}),
    .NPU_QUANT_SHIFT_EN(NPU_QUANT_SHIFT_EN),
    .NPU_ARRAY_EN(NPU_ARRAY_EN),
    .NPU_PSUM_SYSTOLIC_EN(NPU_PSUM_SYSTOLIC_EN),
    .NPU_PSUM_LUT_EN(NPU_PSUM_LUT_EN),
    .NPU_SWAP_WEIGHTS(NPU_SWAP_WEIGHTS),
    .NPU_PSUM_SKEW_EN(NPU_PSUM_SKEW_EN),
    .NPU_COMPUTE_BANK_SWAP(NPU_COMPUTE_BANK_SWAP),
    .UserCLK(Tile_X0Y0_UserCLKo),
    .ConfigBits(ST_ConfigBits[1-1:0])
);

endmodule