# =============================================================================
# CrocoScale SoC — VHDL CPU Complex Filelist: soc
# Auto-generated for mixed-language tools (Vivado read_vhdl)
# =============================================================================

RTL/CPU/core/neorv32_package.vhd
RTL/CPU/bootloader/neorv32_bootrom_image.vhd
RTL/CPU/core/neorv32_bootrom.vhd
RTL/CPU/core/neorv32_bootrom_rom.vhd
RTL/CPU/core/neorv32_bus.vhd
RTL/CPU/core/neorv32_cache.vhd
RTL/CPU/core/neorv32_cache_ram.vhd
RTL/CPU/core/neorv32_cfs.vhd
RTL/CPU/core/neorv32_clint.vhd
RTL/CPU/core/neorv32_cpu.vhd
RTL/CPU/core/neorv32_cpu_alu.vhd
RTL/CPU/core/neorv32_cpu_alu_bitmanip.vhd
RTL/CPU/core/neorv32_cpu_alu_cfu.vhd
RTL/CPU/core/neorv32_cpu_alu_cond.vhd
RTL/CPU/core/neorv32_cpu_alu_crypto.vhd
RTL/CPU/core/neorv32_cpu_alu_fpu.vhd
RTL/CPU/core/neorv32_cpu_alu_muldiv.vhd
RTL/CPU/core/neorv32_cpu_alu_shifter.vhd
RTL/CPU/core/neorv32_cpu_control.vhd
RTL/CPU/core/neorv32_cpu_counters.vhd
RTL/CPU/core/neorv32_cpu_decompressor.vhd
RTL/CPU/core/neorv32_cpu_frontend.vhd
RTL/CPU/core/neorv32_cpu_hwtrig.vhd
RTL/CPU/core/neorv32_cpu_lsu.vhd
RTL/CPU/core/neorv32_cpu_pmp.vhd
RTL/CPU/core/neorv32_cpu_regfile.vhd
RTL/CPU/core/neorv32_cpu_trace.vhd
RTL/CPU/core/neorv32_debug_auth.vhd
RTL/CPU/core/neorv32_debug_dm.vhd
RTL/CPU/core/neorv32_debug_dtm.vhd
RTL/CPU/core/neorv32_dma.vhd
RTL/CPU/core/neorv32_dmem.vhd
RTL/CPU/core/neorv32_dmem_ram.vhd
RTL/CPU/core/neorv32_gpio.vhd
RTL/CPU/core/neorv32_gptmr.vhd
RTL/CPU/core/neorv32_imem.vhd
RTL/CPU/core/neorv32_imem_image.vhd
RTL/CPU/core/neorv32_imem_ram.vhd
RTL/CPU/core/neorv32_imem_rom.vhd
RTL/CPU/core/neorv32_neoled.vhd
RTL/CPU/core/neorv32_onewire.vhd
RTL/CPU/core/neorv32_prim.vhd
RTL/CPU/core/neorv32_pwm.vhd
RTL/CPU/core/neorv32_sdi.vhd
RTL/CPU/core/neorv32_slink.vhd
RTL/CPU/core/neorv32_spi.vhd
RTL/CPU/core/neorv32_sys.vhd
RTL/CPU/core/neorv32_sysinfo.vhd
RTL/CPU/core/neorv32_top.vhd
RTL/CPU/core/neorv32_tracer.vhd
RTL/CPU/core/neorv32_trng.vhd
RTL/CPU/core/neorv32_twd.vhd
RTL/CPU/core/neorv32_twi.vhd
RTL/CPU/core/neorv32_uart.vhd
RTL/CPU/core/neorv32_wdt.vhd
RTL/CPU/core/neorv32_xbus.vhd
RTL/CPU/system_integration/xbus2axi4_bridge.vhd
RTL/Integration/neorv32_axi_wrapper.vhd
