#!/usr/bin/env bash
set -euo pipefail

# Dynamically locate the repository root for portability across host environments
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SRC_RTL="${REPO_ROOT}/RTL"
SRC_MACROS="${REPO_ROOT}/MACROS"
SRC_FLISTS="${REPO_ROOT}/FILE_LISTS"
OUT_DIR="${REPO_ROOT}/VERILOG_MIRROR_GENERATED"
OUT_RTL="${OUT_DIR}/RTL"
OUT_MACROS="${OUT_DIR}/MACROS"
OUT_FLISTS="${OUT_DIR}/FILE_LISTS"

# Ensure ~/.local/bin is in PATH for tools such as sv2v
if [[ -d "${HOME}/.local/bin" ]]; then
    export PATH="${HOME}/.local/bin:${PATH}"
fi

# Verify required tools are available in PATH
if ! command -v sv2v >/dev/null 2>&1; then
    echo "ERROR: sv2v is not found in PATH." >&2
    echo "Please ensure sv2v is installed and added to your PATH." >&2
    exit 1
fi
SV2V_BIN="$(command -v sv2v)"

if ! command -v yosys >/dev/null 2>&1; then
    echo "ERROR: yosys is not found in PATH." >&2
    echo "Please activate an environment containing yosys (with GHDL module support) before running this script." >&2
    exit 1
fi
YOSYS_BIN="$(command -v yosys)"

if ! "${YOSYS_BIN}" -m ghdl -p "help ghdl" >/dev/null 2>&1; then
    echo "ERROR: ${YOSYS_BIN} does not have the GHDL plugin enabled." >&2
    echo "GHDL plugin is required for synthesizing the VHDL NeoRV32 CPU complex." >&2
    exit 1
fi

if ! "${YOSYS_BIN}" -m slang -p "help read_slang" >/dev/null 2>&1; then
    echo "ERROR: ${YOSYS_BIN} does not have the slang plugin enabled." >&2
    echo "Slang plugin is required for reading SystemVerilog in logical equivalence checks." >&2
    exit 1
fi

if ! command -v iverilog >/dev/null 2>&1; then
    echo "ERROR: iverilog is not found in PATH." >&2
    echo "Please ensure Icarus Verilog is installed and added to your PATH for automated linting." >&2
    exit 1
fi
IVERILOG_BIN="$(command -v iverilog)"

# Clean and prepare output directory structure
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_RTL}" "${OUT_MACROS}" "${OUT_FLISTS}"

# Document auto-generated nature of the mirror directory
cat << 'EOF' > "${OUT_DIR}/README.md"
# VERILOG_MIRROR_GENERATED

> **AUTO-GENERATED DIRECTORY — DO NOT EDIT DIRECTLY**
>
> This directory is automatically generated by `scripts/generate_verilog_mirror.sh`.
> All manual hardware modifications must be made to the golden source files:
> - SystemVerilog RTL: `RTL/*.sv`
> - ASIC Subsystem Macros: `MACROS/*.sv` and `MACROS/*.v`
> - VHDL CPU Complex: `RTL/CPU/*.vhd` and `RTL/Integration/neorv32_axi_wrapper.vhd`
>
> Any manual edits made inside this directory will be overwritten on the next generation run.
EOF

# Recreate RTL directory hierarchy in output mirror
find "${SRC_RTL}" -type d ! -path "*/CPU*" | while read -r dir; do
    rel_dir="${dir#"${SRC_RTL}"}"
    if [[ -n "${rel_dir}" ]]; then
        mkdir -p "${OUT_RTL}${rel_dir}"
    fi
done
mkdir -p "${OUT_RTL}/Integration"

# Passthrough static Verilog source files, headers, and initialization tables
find "${SRC_RTL}" -type f \( -name "*.v" -o -name "*.vh" -o -name "*.svh" -o -name "*.hex" -o -name "*.mem" -o -name "*.csv" \) ! -path "*/CPU*" | while read -r src_file; do
    rel_path="${src_file#"${SRC_RTL}/"}"
    mkdir -p "$(dirname "${OUT_RTL}/${rel_path}")"
    cp -p "${src_file}" "${OUT_RTL}/${rel_path}"
done

# Transpile SystemVerilog sources to IEEE Verilog-2001
echo "Transpiling SystemVerilog sources via sv2v (${SV2V_BIN})..."
find "${SRC_RTL}" -type f -name "*.sv" | while read -r sv_file; do
    rel_path="${sv_file#"${SRC_RTL}/"}"
    out_v="${OUT_RTL}/${rel_path%.sv}.v"
    mkdir -p "$(dirname "${out_v}")"
    "${SV2V_BIN}" "${sv_file}" > "${out_v}"
    echo "Transpiled: ${rel_path} -> $(basename "${out_v}")"
done
echo "SystemVerilog transpilation complete."

# Recreate MACROS directory hierarchy in output mirror
if [[ -d "${SRC_MACROS}" ]]; then
    find "${SRC_MACROS}" -type d | while read -r dir; do
        rel_dir="${dir#"${SRC_MACROS}"}"
        if [[ -n "${rel_dir}" ]]; then
            mkdir -p "${OUT_MACROS}${rel_dir}"
        fi
    done

    # Passthrough static Verilog source files, headers, and docs in MACROS
    find "${SRC_MACROS}" -type f \( -name "*.v" -o -name "*.vh" -o -name "*.svh" -o -name "*.md" \) | while read -r src_file; do
        rel_path="${src_file#"${SRC_MACROS}/"}"
        mkdir -p "$(dirname "${OUT_MACROS}/${rel_path}")"
        cp -p "${src_file}" "${OUT_MACROS}/${rel_path}"
    done

    # Transpile SystemVerilog sources in MACROS via sv2v
    echo "Transpiling MACROS SystemVerilog sources via sv2v (${SV2V_BIN})..."
    find "${SRC_MACROS}" -type f -name "*.sv" | while read -r sv_file; do
        rel_path="${sv_file#"${SRC_MACROS}/"}"
        out_v="${OUT_MACROS}/${rel_path%.sv}.v"
        mkdir -p "$(dirname "${out_v}")"
        "${SV2V_BIN}" "${sv_file}" > "${out_v}"
        echo "Transpiled Macro: ${rel_path} -> $(basename "${out_v}")"
    done
    echo "MACROS SystemVerilog transpilation complete."
fi

# Synthesize VHDL NeoRV32 CPU complex into a standalone Verilog module via Yosys GHDL
VHDL_PKG="${SRC_RTL}/CPU/core/neorv32_package.vhd"
VHDL_TOP="neorv32_axi_wrapper"
VHDL_OUT="${OUT_RTL}/Integration/${VHDL_TOP}.v"

echo "Synthesizing VHDL CPU complex (${VHDL_TOP}) via Yosys GHDL..."
vhd_sources=()
for f in "${SRC_RTL}/CPU/core/"*.vhd "${SRC_RTL}/CPU/bootloader/"*.vhd "${SRC_RTL}/CPU/system_integration/"*.vhd "${SRC_RTL}/Integration/${VHDL_TOP}.vhd"; do
    if [[ -f "${f}" && "${f}" != "${VHDL_PKG}" ]]; then
        vhd_sources+=("${f}")
    fi
done

"${YOSYS_BIN}" -m ghdl -p "
    ghdl -fsynopsys --work=neorv32 ${VHDL_PKG} ${vhd_sources[*]} -e ${VHDL_TOP};
    write_verilog -noattr ${VHDL_OUT}
"
echo "VHDL CPU complex synthesized to: ${VHDL_OUT}"

# Replicate and adapt file lists for Verilog mirror consumption
if [[ -d "${SRC_FLISTS}" ]]; then
    find "${SRC_FLISTS}" -type f -name "*.f" | while read -r flist; do
        rel_flist="${flist#"${SRC_FLISTS}/"}"
        out_flist="${OUT_FLISTS}/${rel_flist}"
        mkdir -p "$(dirname "${out_flist}")"

        # Strip carriage returns (CRLF to Unix LF), transform .sv references to .v,
        # and ensure trailing newline
        awk '{
            sub(/\r$/, "");
            sub(/\.sv$/, ".v");
            print;
        }' "${flist}" > "${out_flist}"

        # Ensure trailing newline terminates the final line for parser compatibility
        echo "" >> "${out_flist}"

        # Ensure synthesized VHDL CPU wrapper is included in SoC top file list
        if [[ "$(basename "${flist}")" == "soc.f" && -f "${VHDL_OUT}" ]]; then
            if ! grep -q "neorv32_axi_wrapper.v" "${out_flist}"; then
                echo "RTL/Integration/neorv32_axi_wrapper.v" >> "${out_flist}"
            fi
        fi
        echo "Mirrored file list: ${rel_flist}"
    done
fi

# Two-tier equivalence and structural verification across all transpiled modules
echo "Running automated verification across all SystemVerilog modules..."
lec_passed=0
struct_passed=0
lec_failed=0
lec_skipped=0

inc_dirs=()
while IFS= read -r dir; do
    inc_dirs+=("-I" "${dir}")
done < <(find "${SRC_RTL}" "${SRC_MACROS}" -type d ! -path "*/CPU*")

iv_lib_args=()
while IFS= read -r dir; do
    iv_lib_args+=("-y" "${dir}" "-I" "${dir}")
done < <(find "${OUT_RTL}" "${OUT_MACROS}" -type d)

shared_models=()
while IFS= read -r f; do
    shared_models+=("${f}")
done < <(find "${OUT_RTL}" -type f -name "*pack*.v")

while IFS= read -r sv_file; do
    if [[ "${sv_file}" == "${SRC_MACROS}"* ]]; then
        rel_path="MACROS/${sv_file#"${SRC_MACROS}/"}"
        v_file="${OUT_MACROS}/${sv_file#"${SRC_MACROS}/"}"
        v_file="${v_file%.sv}.v"
    else
        rel_path="RTL/${sv_file#"${SRC_RTL}/"}"
        v_file="${OUT_RTL}/${sv_file#"${SRC_RTL}/"}"
        v_file="${v_file%.sv}.v"
    fi

    if [[ ! -f "${v_file}" ]]; then
        echo "  [SKIP]        ${rel_path} (transpiled Verilog output not found)"
        lec_skipped=$((lec_skipped + 1))
        continue
    fi

    # Extract primary module name
    mod_name=$(sed -n -E 's/^[[:space:]]*module[[:space:]]+([a-zA-Z0-9_]+).*/\1/p' "${sv_file}" | head -n 1)
    if [[ -z "${mod_name}" ]]; then
        echo "  [SKIP]        ${rel_path} (no module declaration found)"
        lec_skipped=$((lec_skipped + 1))
        continue
    fi

    # Tier 1: Formal mathematical equivalence on primary outputs via Yosys Minisat
    tier1_log=$(mktemp)
    if timeout 10s "${YOSYS_BIN}" -q -m slang -p "
        read_slang --top ${mod_name} --ignore-unknown-modules ${inc_dirs[*]} ${sv_file};
        rename ${mod_name} gold;
        read_verilog ${v_file};
        rename ${mod_name} gate;
        proc; memory; async2sync; opt;
        equiv_make gold gate equiv;
        prep -top equiv;
        async2sync;
        equiv_simple;
        equiv_induct;
        equiv_status -assert o:*;
    " > "${tier1_log}" 2>&1; then
        echo "  [LEC PASS]    ${rel_path} (${mod_name})"
        lec_passed=$((lec_passed + 1))
    else
        # Tier 2: Structural elaboration, parameter resolution, and interface audit via Icarus Verilog
        tier2_log=$(mktemp)
        if "${IVERILOG_BIN}" -g2012 -D__ICARUS__ -t null "${iv_lib_args[@]}" "${shared_models[@]}" "${v_file}" > "${tier2_log}" 2>&1; then
            echo "  [STRUCT PASS] ${rel_path} (${mod_name})"
            struct_passed=$((struct_passed + 1))
        else
            err_msg=$(head -n 2 "${tier2_log}" | tail -n 1 || echo "Structural elaboration failed")
            echo "  [FAIL]        ${rel_path} (${mod_name}) - ${err_msg}"
            lec_failed=$((lec_failed + 1))
        fi
        rm -f "${tier2_log}"
    fi
    rm -f "${tier1_log}"
done < <(find "${SRC_RTL}" "${SRC_MACROS}" -type f -name "*.sv" | sort)

echo ""
echo "Verification Summary:"
echo "  Tier 1 Formal SAT Proofs Passed:  ${lec_passed}"
echo "  Tier 2 Structural Audits Passed: ${struct_passed}"
echo "  Failed:                          ${lec_failed}"
echo "  Skipped:                         ${lec_skipped}"

# Automated post-generation Icarus Verilog lint check on complete SoC
echo "Running automated Icarus Verilog linter / elaboration on full SoC..."
(
    cd "${OUT_DIR}"
    "${IVERILOG_BIN}" -g2012 -D__ICARUS__ -f FILE_LISTS/soc.f -s crocoscale_soc -o /dev/null
)
echo "Icarus Verilog lint check passed: Full SoC elaboration successful."

# Automated post-generation Icarus Verilog lint check on ASIC macros
echo "Running automated Icarus Verilog linter on ASIC macros..."
(
    cd "${OUT_DIR}"
    "${IVERILOG_BIN}" -g2012 -D__ICARUS__ -f FILE_LISTS/macros.f -o /dev/null
)
echo "Icarus Verilog lint check passed: ASIC macros elaboration successful."

echo "Verilog mirror generation complete at: ${OUT_DIR}"
