module AXIL_S_IO_W
    #(
`ifdef EMULATION
        parameter [639:0] Tile_X0Y0_Emulate_Bitstream=640'b0,
        parameter [639:0] Tile_X0Y1_Emulate_Bitstream=640'b0,
        parameter [639:0] Tile_X0Y2_Emulate_Bitstream=640'b0,
        parameter [639:0] Tile_X0Y3_Emulate_Bitstream=640'b0,
`endif
        parameter MaxFramesPerCol=20,
        parameter FrameBitsPerRow=32
    )
    (
    //Tile_X0Y0_Direction.NORTH
        output  [3:0] Tile_X0Y0_N1BEG, //TilePort({N} OUTPUT N1BEG[3:0])
        output  [7:0] Tile_X0Y0_N2BEG, //TilePort({N} OUTPUT N2BEG[7:0])
        output  [7:0] Tile_X0Y0_N2BEGb, //TilePort({N} OUTPUT N2BEGb[7:0])
        output  [15:0] Tile_X0Y0_N4BEG, //TilePort({N} OUTPUT N4BEG[3:0])
        input  [3:0] Tile_X0Y0_S1END, //TilePort({N} INPUT S1END[3:0])
        input  [7:0] Tile_X0Y0_S2MID, //TilePort({N} INPUT S2MID[7:0])
        input  [7:0] Tile_X0Y0_S2END, //TilePort({N} INPUT S2END[7:0])
        input  [15:0] Tile_X0Y0_S4END, //TilePort({N} INPUT S4END[3:0])
    //Tile_X0Y0_Direction.WEST
        input  [3:0] Tile_X0Y0_W1END, //TilePort({E} INPUT W1END[3:0])
        input  [7:0] Tile_X0Y0_W2MID, //TilePort({E} INPUT W2MID[7:0])
        input  [7:0] Tile_X0Y0_W2END, //TilePort({E} INPUT W2END[7:0])
        input  [15:0] Tile_X0Y0_WW4END, //TilePort({E} INPUT WW4END[3:0])
        input  [11:0] Tile_X0Y0_W6END, //TilePort({E} INPUT W6END[1:0])
        output  [3:0] Tile_X0Y0_E1BEG, //TilePort({E} OUTPUT E1BEG[3:0])
        output  [7:0] Tile_X0Y0_E2BEG, //TilePort({E} OUTPUT E2BEG[7:0])
        output  [7:0] Tile_X0Y0_E2BEGb, //TilePort({E} OUTPUT E2BEGb[7:0])
        output  [15:0] Tile_X0Y0_EE4BEG, //TilePort({E} OUTPUT EE4BEG[3:0])
        output  [11:0] Tile_X0Y0_E6BEG, //TilePort({E} OUTPUT E6BEG[1:0])
    //Tile_X0Y1_Direction.WEST
        input  [3:0] Tile_X0Y1_W1END, //TilePort({E} INPUT W1END[3:0])
        input  [7:0] Tile_X0Y1_W2MID, //TilePort({E} INPUT W2MID[7:0])
        input  [7:0] Tile_X0Y1_W2END, //TilePort({E} INPUT W2END[7:0])
        input  [15:0] Tile_X0Y1_WW4END, //TilePort({E} INPUT WW4END[3:0])
        input  [11:0] Tile_X0Y1_W6END, //TilePort({E} INPUT W6END[1:0])
        output  [3:0] Tile_X0Y1_E1BEG, //TilePort({E} OUTPUT E1BEG[3:0])
        output  [7:0] Tile_X0Y1_E2BEG, //TilePort({E} OUTPUT E2BEG[7:0])
        output  [7:0] Tile_X0Y1_E2BEGb, //TilePort({E} OUTPUT E2BEGb[7:0])
        output  [15:0] Tile_X0Y1_EE4BEG, //TilePort({E} OUTPUT EE4BEG[3:0])
        output  [11:0] Tile_X0Y1_E6BEG, //TilePort({E} OUTPUT E6BEG[1:0])
    //Tile_X0Y2_Direction.WEST
        input  [3:0] Tile_X0Y2_W1END, //TilePort({E} INPUT W1END[3:0])
        input  [7:0] Tile_X0Y2_W2MID, //TilePort({E} INPUT W2MID[7:0])
        input  [7:0] Tile_X0Y2_W2END, //TilePort({E} INPUT W2END[7:0])
        input  [15:0] Tile_X0Y2_WW4END, //TilePort({E} INPUT WW4END[3:0])
        input  [11:0] Tile_X0Y2_W6END, //TilePort({E} INPUT W6END[1:0])
        output  [3:0] Tile_X0Y2_E1BEG, //TilePort({E} OUTPUT E1BEG[3:0])
        output  [7:0] Tile_X0Y2_E2BEG, //TilePort({E} OUTPUT E2BEG[7:0])
        output  [7:0] Tile_X0Y2_E2BEGb, //TilePort({E} OUTPUT E2BEGb[7:0])
        output  [15:0] Tile_X0Y2_EE4BEG, //TilePort({E} OUTPUT EE4BEG[3:0])
        output  [11:0] Tile_X0Y2_E6BEG, //TilePort({E} OUTPUT E6BEG[1:0])
    //Tile_X0Y3_Direction.WEST
        input  [3:0] Tile_X0Y3_W1END, //TilePort({E} INPUT W1END[3:0])
        input  [7:0] Tile_X0Y3_W2MID, //TilePort({E} INPUT W2MID[7:0])
        input  [7:0] Tile_X0Y3_W2END, //TilePort({E} INPUT W2END[7:0])
        input  [15:0] Tile_X0Y3_WW4END, //TilePort({E} INPUT WW4END[3:0])
        input  [11:0] Tile_X0Y3_W6END, //TilePort({E} INPUT W6END[1:0])
        output  [3:0] Tile_X0Y3_E1BEG, //TilePort({E} OUTPUT E1BEG[3:0])
        output  [7:0] Tile_X0Y3_E2BEG, //TilePort({E} OUTPUT E2BEG[7:0])
        output  [7:0] Tile_X0Y3_E2BEGb, //TilePort({E} OUTPUT E2BEGb[7:0])
        output  [15:0] Tile_X0Y3_EE4BEG, //TilePort({E} OUTPUT EE4BEG[3:0])
        output  [11:0] Tile_X0Y3_E6BEG, //TilePort({E} OUTPUT E6BEG[1:0])
    //Tile_X0Y3_Direction.NORTH
        input  [3:0] Tile_X0Y3_N1END, //TilePort({S} INPUT N1END[3:0])
        input  [7:0] Tile_X0Y3_N2MID, //TilePort({S} INPUT N2MID[7:0])
        input  [7:0] Tile_X0Y3_N2END, //TilePort({S} INPUT N2END[7:0])
        input  [15:0] Tile_X0Y3_N4END, //TilePort({S} INPUT N4END[3:0])
        output  [3:0] Tile_X0Y3_S1BEG, //TilePort({S} OUTPUT S1BEG[3:0])
        output  [7:0] Tile_X0Y3_S2BEG, //TilePort({S} OUTPUT S2BEG[7:0])
        output  [7:0] Tile_X0Y3_S2BEGb, //TilePort({S} OUTPUT S2BEGb[7:0])
        output  [15:0] Tile_X0Y3_S4BEG, //TilePort({S} OUTPUT S4BEG[3:0])
    //Tile IO ports from BELs
    //SuperTile BEL IO ports
        input  AXIL_S_SOC_AWADDR0,
        input  AXIL_S_SOC_AWADDR1,
        input  AXIL_S_SOC_AWADDR2,
        input  AXIL_S_SOC_AWADDR3,
        input  AXIL_S_SOC_AWADDR4,
        input  AXIL_S_SOC_AWADDR5,
        input  AXIL_S_SOC_AWADDR6,
        input  AXIL_S_SOC_AWADDR7,
        input  AXIL_S_SOC_AWADDR8,
        input  AXIL_S_SOC_AWADDR9,
        input  AXIL_S_SOC_AWVALID,
        input  AXIL_S_SOC_WDATA0,
        input  AXIL_S_SOC_WDATA1,
        input  AXIL_S_SOC_WDATA2,
        input  AXIL_S_SOC_WDATA3,
        input  AXIL_S_SOC_WDATA4,
        input  AXIL_S_SOC_WDATA5,
        input  AXIL_S_SOC_WDATA6,
        input  AXIL_S_SOC_WDATA7,
        input  AXIL_S_SOC_WDATA8,
        input  AXIL_S_SOC_WDATA9,
        input  AXIL_S_SOC_WDATA10,
        input  AXIL_S_SOC_WDATA11,
        input  AXIL_S_SOC_WDATA12,
        input  AXIL_S_SOC_WDATA13,
        input  AXIL_S_SOC_WDATA14,
        input  AXIL_S_SOC_WDATA15,
        input  AXIL_S_SOC_WDATA16,
        input  AXIL_S_SOC_WDATA17,
        input  AXIL_S_SOC_WDATA18,
        input  AXIL_S_SOC_WDATA19,
        input  AXIL_S_SOC_WDATA20,
        input  AXIL_S_SOC_WDATA21,
        input  AXIL_S_SOC_WDATA22,
        input  AXIL_S_SOC_WDATA23,
        input  AXIL_S_SOC_WDATA24,
        input  AXIL_S_SOC_WDATA25,
        input  AXIL_S_SOC_WDATA26,
        input  AXIL_S_SOC_WDATA27,
        input  AXIL_S_SOC_WDATA28,
        input  AXIL_S_SOC_WDATA29,
        input  AXIL_S_SOC_WDATA30,
        input  AXIL_S_SOC_WDATA31,
        input  AXIL_S_SOC_WSTRB0,
        input  AXIL_S_SOC_WSTRB1,
        input  AXIL_S_SOC_WSTRB2,
        input  AXIL_S_SOC_WSTRB3,
        input  AXIL_S_SOC_WVALID,
        input  AXIL_S_SOC_BREADY,
        input  AXIL_S_SOC_ARADDR0,
        input  AXIL_S_SOC_ARADDR1,
        input  AXIL_S_SOC_ARADDR2,
        input  AXIL_S_SOC_ARADDR3,
        input  AXIL_S_SOC_ARADDR4,
        input  AXIL_S_SOC_ARADDR5,
        input  AXIL_S_SOC_ARADDR6,
        input  AXIL_S_SOC_ARADDR7,
        input  AXIL_S_SOC_ARADDR8,
        input  AXIL_S_SOC_ARADDR9,
        input  AXIL_S_SOC_ARVALID,
        input  AXIL_S_SOC_RREADY,
        output  AXIL_S_SOC_AWREADY,
        output  AXIL_S_SOC_WREADY,
        output  AXIL_S_SOC_BRESP0,
        output  AXIL_S_SOC_BRESP1,
        output  AXIL_S_SOC_BVALID,
        output  AXIL_S_SOC_ARREADY,
        output  AXIL_S_SOC_RDATA0,
        output  AXIL_S_SOC_RDATA1,
        output  AXIL_S_SOC_RDATA2,
        output  AXIL_S_SOC_RDATA3,
        output  AXIL_S_SOC_RDATA4,
        output  AXIL_S_SOC_RDATA5,
        output  AXIL_S_SOC_RDATA6,
        output  AXIL_S_SOC_RDATA7,
        output  AXIL_S_SOC_RDATA8,
        output  AXIL_S_SOC_RDATA9,
        output  AXIL_S_SOC_RDATA10,
        output  AXIL_S_SOC_RDATA11,
        output  AXIL_S_SOC_RDATA12,
        output  AXIL_S_SOC_RDATA13,
        output  AXIL_S_SOC_RDATA14,
        output  AXIL_S_SOC_RDATA15,
        output  AXIL_S_SOC_RDATA16,
        output  AXIL_S_SOC_RDATA17,
        output  AXIL_S_SOC_RDATA18,
        output  AXIL_S_SOC_RDATA19,
        output  AXIL_S_SOC_RDATA20,
        output  AXIL_S_SOC_RDATA21,
        output  AXIL_S_SOC_RDATA22,
        output  AXIL_S_SOC_RDATA23,
        output  AXIL_S_SOC_RDATA24,
        output  AXIL_S_SOC_RDATA25,
        output  AXIL_S_SOC_RDATA26,
        output  AXIL_S_SOC_RDATA27,
        output  AXIL_S_SOC_RDATA28,
        output  AXIL_S_SOC_RDATA29,
        output  AXIL_S_SOC_RDATA30,
        output  AXIL_S_SOC_RDATA31,
        output  AXIL_S_SOC_RRESP0,
        output  AXIL_S_SOC_RRESP1,
        output  AXIL_S_SOC_RVALID,
        output  [MaxFramesPerCol-1:0] Tile_X0Y0_FrameStrobe_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y0_FrameData, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X0Y0_FrameData_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y1_FrameData, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X0Y1_FrameData_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y2_FrameData, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X0Y2_FrameData_O, //CONFIG_PORT
        input  [FrameBitsPerRow-1:0] Tile_X0Y3_FrameData, //CONFIG_PORT
        input  [MaxFramesPerCol-1:0] Tile_X0Y3_FrameStrobe, //CONFIG_PORT
        output  [FrameBitsPerRow-1:0] Tile_X0Y3_FrameData_O, //CONFIG_PORT
        output  Tile_X0Y0_UserCLKo,
        input  Tile_X0Y3_UserCLK
);

 //signal declarations
 //SJUMP signals (child tile -> supertile SM)
    wire[12-1:0] AXIL_S_IO_W_3_BASE_TO_TOP;
    wire[12-1:0] AXIL_S_IO_W_2_BASE_TO_TOP;
    wire[12-1:0] AXIL_S_IO_W_1_BASE_TO_TOP;
    wire[12-1:0] AXIL_S_IO_W_0_BASE_TO_TOP;
 //SJUMP signals (supertile SM -> child tile)
    wire[16-1:0] AXIL_S_IO_W_3_TOP_TO_BASE;
    wire[16-1:0] AXIL_S_IO_W_2_TOP_TO_BASE;
    wire[16-1:0] AXIL_S_IO_W_1_TOP_TO_BASE;
    wire[16-1:0] AXIL_S_IO_W_0_TOP_TO_BASE;
 //BEL pin signals (BEL <-> supertile SM)
    wire AXIL_S_FAB_AWREADY;
    wire AXIL_S_FAB_WREADY;
    wire AXIL_S_FAB_BRESP0;
    wire AXIL_S_FAB_BRESP1;
    wire AXIL_S_FAB_BVALID;
    wire AXIL_S_FAB_ARREADY;
    wire AXIL_S_FAB_RDATA0;
    wire AXIL_S_FAB_RDATA1;
    wire AXIL_S_FAB_RDATA2;
    wire AXIL_S_FAB_RDATA3;
    wire AXIL_S_FAB_RDATA4;
    wire AXIL_S_FAB_RDATA5;
    wire AXIL_S_FAB_RDATA6;
    wire AXIL_S_FAB_RDATA7;
    wire AXIL_S_FAB_RDATA8;
    wire AXIL_S_FAB_RDATA9;
    wire AXIL_S_FAB_RDATA10;
    wire AXIL_S_FAB_RDATA11;
    wire AXIL_S_FAB_RDATA12;
    wire AXIL_S_FAB_RDATA13;
    wire AXIL_S_FAB_RDATA14;
    wire AXIL_S_FAB_RDATA15;
    wire AXIL_S_FAB_RDATA16;
    wire AXIL_S_FAB_RDATA17;
    wire AXIL_S_FAB_RDATA18;
    wire AXIL_S_FAB_RDATA19;
    wire AXIL_S_FAB_RDATA20;
    wire AXIL_S_FAB_RDATA21;
    wire AXIL_S_FAB_RDATA22;
    wire AXIL_S_FAB_RDATA23;
    wire AXIL_S_FAB_RDATA24;
    wire AXIL_S_FAB_RDATA25;
    wire AXIL_S_FAB_RDATA26;
    wire AXIL_S_FAB_RDATA27;
    wire AXIL_S_FAB_RDATA28;
    wire AXIL_S_FAB_RDATA29;
    wire AXIL_S_FAB_RDATA30;
    wire AXIL_S_FAB_RDATA31;
    wire AXIL_S_FAB_RRESP0;
    wire AXIL_S_FAB_RRESP1;
    wire AXIL_S_FAB_RVALID;
    wire AXIL_S_FAB_AWADDR0;
    wire AXIL_S_FAB_AWADDR1;
    wire AXIL_S_FAB_AWADDR2;
    wire AXIL_S_FAB_AWADDR3;
    wire AXIL_S_FAB_AWADDR4;
    wire AXIL_S_FAB_AWADDR5;
    wire AXIL_S_FAB_AWADDR6;
    wire AXIL_S_FAB_AWADDR7;
    wire AXIL_S_FAB_AWADDR8;
    wire AXIL_S_FAB_AWADDR9;
    wire AXIL_S_FAB_AWVALID;
    wire AXIL_S_FAB_WDATA0;
    wire AXIL_S_FAB_WDATA1;
    wire AXIL_S_FAB_WDATA2;
    wire AXIL_S_FAB_WDATA3;
    wire AXIL_S_FAB_WDATA4;
    wire AXIL_S_FAB_WDATA5;
    wire AXIL_S_FAB_WDATA6;
    wire AXIL_S_FAB_WDATA7;
    wire AXIL_S_FAB_WDATA8;
    wire AXIL_S_FAB_WDATA9;
    wire AXIL_S_FAB_WDATA10;
    wire AXIL_S_FAB_WDATA11;
    wire AXIL_S_FAB_WDATA12;
    wire AXIL_S_FAB_WDATA13;
    wire AXIL_S_FAB_WDATA14;
    wire AXIL_S_FAB_WDATA15;
    wire AXIL_S_FAB_WDATA16;
    wire AXIL_S_FAB_WDATA17;
    wire AXIL_S_FAB_WDATA18;
    wire AXIL_S_FAB_WDATA19;
    wire AXIL_S_FAB_WDATA20;
    wire AXIL_S_FAB_WDATA21;
    wire AXIL_S_FAB_WDATA22;
    wire AXIL_S_FAB_WDATA23;
    wire AXIL_S_FAB_WDATA24;
    wire AXIL_S_FAB_WDATA25;
    wire AXIL_S_FAB_WDATA26;
    wire AXIL_S_FAB_WDATA27;
    wire AXIL_S_FAB_WDATA28;
    wire AXIL_S_FAB_WDATA29;
    wire AXIL_S_FAB_WDATA30;
    wire AXIL_S_FAB_WDATA31;
    wire AXIL_S_FAB_WSTRB0;
    wire AXIL_S_FAB_WSTRB1;
    wire AXIL_S_FAB_WSTRB2;
    wire AXIL_S_FAB_WSTRB3;
    wire AXIL_S_FAB_WVALID;
    wire AXIL_S_FAB_BREADY;
    wire AXIL_S_FAB_ARADDR0;
    wire AXIL_S_FAB_ARADDR1;
    wire AXIL_S_FAB_ARADDR2;
    wire AXIL_S_FAB_ARADDR3;
    wire AXIL_S_FAB_ARADDR4;
    wire AXIL_S_FAB_ARADDR5;
    wire AXIL_S_FAB_ARADDR6;
    wire AXIL_S_FAB_ARADDR7;
    wire AXIL_S_FAB_ARADDR8;
    wire AXIL_S_FAB_ARADDR9;
    wire AXIL_S_FAB_ARVALID;
    wire AXIL_S_FAB_RREADY;
 //Tile_X0Y0_Direction.NORTH
    wire[3:0] Tile_X0Y0_S1BEG; //TilePort({S} OUTPUT S1BEG[3:0])
    wire[7:0] Tile_X0Y0_S2BEG; //TilePort({S} OUTPUT S2BEG[7:0])
    wire[7:0] Tile_X0Y0_S2BEGb; //TilePort({S} OUTPUT S2BEGb[7:0])
    wire[15:0] Tile_X0Y0_S4BEG; //TilePort({S} OUTPUT S4BEG[3:0])
 //Tile_X0Y1_Direction.NORTH
    wire[3:0] Tile_X0Y1_N1BEG; //TilePort({N} OUTPUT N1BEG[3:0])
    wire[7:0] Tile_X0Y1_N2BEG; //TilePort({N} OUTPUT N2BEG[7:0])
    wire[7:0] Tile_X0Y1_N2BEGb; //TilePort({N} OUTPUT N2BEGb[7:0])
    wire[15:0] Tile_X0Y1_N4BEG; //TilePort({N} OUTPUT N4BEG[3:0])
 //Tile_X0Y1_Direction.NORTH
    wire[3:0] Tile_X0Y1_S1BEG; //TilePort({S} OUTPUT S1BEG[3:0])
    wire[7:0] Tile_X0Y1_S2BEG; //TilePort({S} OUTPUT S2BEG[7:0])
    wire[7:0] Tile_X0Y1_S2BEGb; //TilePort({S} OUTPUT S2BEGb[7:0])
    wire[15:0] Tile_X0Y1_S4BEG; //TilePort({S} OUTPUT S4BEG[3:0])
 //Tile_X0Y2_Direction.NORTH
    wire[3:0] Tile_X0Y2_N1BEG; //TilePort({N} OUTPUT N1BEG[3:0])
    wire[7:0] Tile_X0Y2_N2BEG; //TilePort({N} OUTPUT N2BEG[7:0])
    wire[7:0] Tile_X0Y2_N2BEGb; //TilePort({N} OUTPUT N2BEGb[7:0])
    wire[15:0] Tile_X0Y2_N4BEG; //TilePort({N} OUTPUT N4BEG[3:0])
 //Tile_X0Y2_Direction.NORTH
    wire[3:0] Tile_X0Y2_S1BEG; //TilePort({S} OUTPUT S1BEG[3:0])
    wire[7:0] Tile_X0Y2_S2BEG; //TilePort({S} OUTPUT S2BEG[7:0])
    wire[7:0] Tile_X0Y2_S2BEGb; //TilePort({S} OUTPUT S2BEGb[7:0])
    wire[15:0] Tile_X0Y2_S4BEG; //TilePort({S} OUTPUT S4BEG[3:0])
 //Tile_X0Y3_Direction.NORTH
    wire[3:0] Tile_X0Y3_N1BEG; //TilePort({N} OUTPUT N1BEG[3:0])
    wire[7:0] Tile_X0Y3_N2BEG; //TilePort({N} OUTPUT N2BEG[7:0])
    wire[7:0] Tile_X0Y3_N2BEGb; //TilePort({N} OUTPUT N2BEGb[7:0])
    wire[15:0] Tile_X0Y3_N4BEG; //TilePort({N} OUTPUT N4BEG[3:0])
    wire[MaxFramesPerCol-1:0] Tile_X0Y1_FrameStrobe_O;
    wire Tile_X0Y1_UserCLKo;
    wire[MaxFramesPerCol-1:0] Tile_X0Y2_FrameStrobe_O;
    wire Tile_X0Y2_UserCLKo;
    wire[MaxFramesPerCol-1:0] Tile_X0Y3_FrameStrobe_O;
    wire Tile_X0Y3_UserCLKo;
    wire[6-1:0] ST_ConfigBits;
    wire[6-1:0] ST_ConfigBits_N;

AXIL_S_IO_W_3
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y0_Emulate_Bitstream)
    )
`endif
    Tile_X0Y0_AXIL_S_IO_W_3
    (
    .N1END(Tile_X0Y1_N1BEG),
    .N2MID(Tile_X0Y1_N2BEG),
    .N2END(Tile_X0Y1_N2BEGb),
    .N4END(Tile_X0Y1_N4BEG),
    .S1END(Tile_X0Y0_S1END),
    .S2MID(Tile_X0Y0_S2MID),
    .S2END(Tile_X0Y0_S2END),
    .S4END(Tile_X0Y0_S4END),
    .W1END(Tile_X0Y0_W1END),
    .W2MID(Tile_X0Y0_W2MID),
    .W2END(Tile_X0Y0_W2END),
    .WW4END(Tile_X0Y0_WW4END),
    .W6END(Tile_X0Y0_W6END),
    .N1BEG(Tile_X0Y0_N1BEG),
    .N2BEG(Tile_X0Y0_N2BEG),
    .N2BEGb(Tile_X0Y0_N2BEGb),
    .N4BEG(Tile_X0Y0_N4BEG),
    .E1BEG(Tile_X0Y0_E1BEG),
    .E2BEG(Tile_X0Y0_E2BEG),
    .E2BEGb(Tile_X0Y0_E2BEGb),
    .EE4BEG(Tile_X0Y0_EE4BEG),
    .E6BEG(Tile_X0Y0_E6BEG),
    .S1BEG(Tile_X0Y0_S1BEG),
    .S2BEG(Tile_X0Y0_S2BEG),
    .S2BEGb(Tile_X0Y0_S2BEGb),
    .S4BEG(Tile_X0Y0_S4BEG),
    .BASE_TO_TOP(AXIL_S_IO_W_3_BASE_TO_TOP),
    .TOP_TO_BASE(AXIL_S_IO_W_3_TOP_TO_BASE),
    .UserCLK(Tile_X0Y1_UserCLKo),
    .UserCLKo(Tile_X0Y0_UserCLKo),
    .FrameData(Tile_X0Y0_FrameData),
    .FrameData_O(Tile_X0Y0_FrameData_O),
    .FrameStrobe(Tile_X0Y1_FrameStrobe_O),
    .FrameStrobe_O(Tile_X0Y0_FrameStrobe_O)
);

AXIL_S_IO_W_2
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y1_Emulate_Bitstream)
    )
`endif
    Tile_X0Y1_AXIL_S_IO_W_2
    (
    .N1END(Tile_X0Y2_N1BEG),
    .N2MID(Tile_X0Y2_N2BEG),
    .N2END(Tile_X0Y2_N2BEGb),
    .N4END(Tile_X0Y2_N4BEG),
    .S1END(Tile_X0Y0_S1BEG),
    .S2MID(Tile_X0Y0_S2BEG),
    .S2END(Tile_X0Y0_S2BEGb),
    .S4END(Tile_X0Y0_S4BEG),
    .W1END(Tile_X0Y1_W1END),
    .W2MID(Tile_X0Y1_W2MID),
    .W2END(Tile_X0Y1_W2END),
    .WW4END(Tile_X0Y1_WW4END),
    .W6END(Tile_X0Y1_W6END),
    .N1BEG(Tile_X0Y1_N1BEG),
    .N2BEG(Tile_X0Y1_N2BEG),
    .N2BEGb(Tile_X0Y1_N2BEGb),
    .N4BEG(Tile_X0Y1_N4BEG),
    .E1BEG(Tile_X0Y1_E1BEG),
    .E2BEG(Tile_X0Y1_E2BEG),
    .E2BEGb(Tile_X0Y1_E2BEGb),
    .EE4BEG(Tile_X0Y1_EE4BEG),
    .E6BEG(Tile_X0Y1_E6BEG),
    .S1BEG(Tile_X0Y1_S1BEG),
    .S2BEG(Tile_X0Y1_S2BEG),
    .S2BEGb(Tile_X0Y1_S2BEGb),
    .S4BEG(Tile_X0Y1_S4BEG),
    .BASE_TO_TOP(AXIL_S_IO_W_2_BASE_TO_TOP),
    .TOP_TO_BASE(AXIL_S_IO_W_2_TOP_TO_BASE),
    .UserCLK(Tile_X0Y2_UserCLKo),
    .UserCLKo(Tile_X0Y1_UserCLKo),
    .FrameData(Tile_X0Y1_FrameData),
    .FrameData_O(Tile_X0Y1_FrameData_O),
    .FrameStrobe(Tile_X0Y2_FrameStrobe_O),
    .FrameStrobe_O(Tile_X0Y1_FrameStrobe_O)
);

AXIL_S_IO_W_1
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y2_Emulate_Bitstream)
    )
`endif
    Tile_X0Y2_AXIL_S_IO_W_1
    (
    .N1END(Tile_X0Y3_N1BEG),
    .N2MID(Tile_X0Y3_N2BEG),
    .N2END(Tile_X0Y3_N2BEGb),
    .N4END(Tile_X0Y3_N4BEG),
    .S1END(Tile_X0Y1_S1BEG),
    .S2MID(Tile_X0Y1_S2BEG),
    .S2END(Tile_X0Y1_S2BEGb),
    .S4END(Tile_X0Y1_S4BEG),
    .W1END(Tile_X0Y2_W1END),
    .W2MID(Tile_X0Y2_W2MID),
    .W2END(Tile_X0Y2_W2END),
    .WW4END(Tile_X0Y2_WW4END),
    .W6END(Tile_X0Y2_W6END),
    .N1BEG(Tile_X0Y2_N1BEG),
    .N2BEG(Tile_X0Y2_N2BEG),
    .N2BEGb(Tile_X0Y2_N2BEGb),
    .N4BEG(Tile_X0Y2_N4BEG),
    .E1BEG(Tile_X0Y2_E1BEG),
    .E2BEG(Tile_X0Y2_E2BEG),
    .E2BEGb(Tile_X0Y2_E2BEGb),
    .EE4BEG(Tile_X0Y2_EE4BEG),
    .E6BEG(Tile_X0Y2_E6BEG),
    .S1BEG(Tile_X0Y2_S1BEG),
    .S2BEG(Tile_X0Y2_S2BEG),
    .S2BEGb(Tile_X0Y2_S2BEGb),
    .S4BEG(Tile_X0Y2_S4BEG),
    .BASE_TO_TOP(AXIL_S_IO_W_1_BASE_TO_TOP),
    .TOP_TO_BASE(AXIL_S_IO_W_1_TOP_TO_BASE),
    .UserCLK(Tile_X0Y3_UserCLKo),
    .UserCLKo(Tile_X0Y2_UserCLKo),
    .FrameData(Tile_X0Y2_FrameData),
    .FrameData_O(Tile_X0Y2_FrameData_O),
    .FrameStrobe(Tile_X0Y3_FrameStrobe_O),
    .FrameStrobe_O(Tile_X0Y2_FrameStrobe_O)
);

AXIL_S_IO_W_0
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y3_Emulate_Bitstream)
    )
`endif
    Tile_X0Y3_AXIL_S_IO_W_0
    (
    .N1END(Tile_X0Y3_N1END),
    .N2MID(Tile_X0Y3_N2MID),
    .N2END(Tile_X0Y3_N2END),
    .N4END(Tile_X0Y3_N4END),
    .S1END(Tile_X0Y2_S1BEG),
    .S2MID(Tile_X0Y2_S2BEG),
    .S2END(Tile_X0Y2_S2BEGb),
    .S4END(Tile_X0Y2_S4BEG),
    .W1END(Tile_X0Y3_W1END),
    .W2MID(Tile_X0Y3_W2MID),
    .W2END(Tile_X0Y3_W2END),
    .WW4END(Tile_X0Y3_WW4END),
    .W6END(Tile_X0Y3_W6END),
    .N1BEG(Tile_X0Y3_N1BEG),
    .N2BEG(Tile_X0Y3_N2BEG),
    .N2BEGb(Tile_X0Y3_N2BEGb),
    .N4BEG(Tile_X0Y3_N4BEG),
    .E1BEG(Tile_X0Y3_E1BEG),
    .E2BEG(Tile_X0Y3_E2BEG),
    .E2BEGb(Tile_X0Y3_E2BEGb),
    .EE4BEG(Tile_X0Y3_EE4BEG),
    .E6BEG(Tile_X0Y3_E6BEG),
    .S1BEG(Tile_X0Y3_S1BEG),
    .S2BEG(Tile_X0Y3_S2BEG),
    .S2BEGb(Tile_X0Y3_S2BEGb),
    .S4BEG(Tile_X0Y3_S4BEG),
    .BASE_TO_TOP(AXIL_S_IO_W_0_BASE_TO_TOP),
    .TOP_TO_BASE(AXIL_S_IO_W_0_TOP_TO_BASE),
    .UserCLK(Tile_X0Y3_UserCLK),
    .UserCLKo(Tile_X0Y3_UserCLKo),
    .FrameData(Tile_X0Y3_FrameData),
    .FrameData_O(Tile_X0Y3_FrameData_O),
    .FrameStrobe(Tile_X0Y3_FrameStrobe),
    .FrameStrobe_O(Tile_X0Y3_FrameStrobe_O)
);

AXIL_S_IO_W_ConfigMem
`ifdef EMULATION
    #(
    .Emulate_Bitstream(Tile_X0Y3_Emulate_Bitstream)
    )
`endif
    Inst_AXIL_S_IO_W_ConfigMem
    (
    .FrameData(Tile_X0Y3_FrameData),
    .FrameStrobe(Tile_X0Y3_FrameStrobe),
    .ConfigBits(ST_ConfigBits[6-1:0]),
    .ConfigBits_N(ST_ConfigBits_N[6-1:0])
);

AXIL_S_IO_W_switch_matrix Inst_AXIL_S_IO_W_switch_matrix (
    .AXIL_S_IO_W_3_BASE_TO_TOP0(AXIL_S_IO_W_3_BASE_TO_TOP[0]),
    .AXIL_S_IO_W_3_BASE_TO_TOP1(AXIL_S_IO_W_3_BASE_TO_TOP[1]),
    .AXIL_S_IO_W_3_BASE_TO_TOP2(AXIL_S_IO_W_3_BASE_TO_TOP[2]),
    .AXIL_S_IO_W_3_BASE_TO_TOP3(AXIL_S_IO_W_3_BASE_TO_TOP[3]),
    .AXIL_S_IO_W_3_BASE_TO_TOP4(AXIL_S_IO_W_3_BASE_TO_TOP[4]),
    .AXIL_S_IO_W_3_BASE_TO_TOP5(AXIL_S_IO_W_3_BASE_TO_TOP[5]),
    .AXIL_S_IO_W_3_BASE_TO_TOP6(AXIL_S_IO_W_3_BASE_TO_TOP[6]),
    .AXIL_S_IO_W_3_BASE_TO_TOP7(AXIL_S_IO_W_3_BASE_TO_TOP[7]),
    .AXIL_S_IO_W_3_BASE_TO_TOP8(AXIL_S_IO_W_3_BASE_TO_TOP[8]),
    .AXIL_S_IO_W_3_BASE_TO_TOP9(AXIL_S_IO_W_3_BASE_TO_TOP[9]),
    .AXIL_S_IO_W_3_BASE_TO_TOP10(AXIL_S_IO_W_3_BASE_TO_TOP[10]),
    .AXIL_S_IO_W_3_BASE_TO_TOP11(AXIL_S_IO_W_3_BASE_TO_TOP[11]),
    .AXIL_S_IO_W_2_BASE_TO_TOP0(AXIL_S_IO_W_2_BASE_TO_TOP[0]),
    .AXIL_S_IO_W_2_BASE_TO_TOP1(AXIL_S_IO_W_2_BASE_TO_TOP[1]),
    .AXIL_S_IO_W_2_BASE_TO_TOP2(AXIL_S_IO_W_2_BASE_TO_TOP[2]),
    .AXIL_S_IO_W_2_BASE_TO_TOP3(AXIL_S_IO_W_2_BASE_TO_TOP[3]),
    .AXIL_S_IO_W_2_BASE_TO_TOP4(AXIL_S_IO_W_2_BASE_TO_TOP[4]),
    .AXIL_S_IO_W_2_BASE_TO_TOP5(AXIL_S_IO_W_2_BASE_TO_TOP[5]),
    .AXIL_S_IO_W_2_BASE_TO_TOP6(AXIL_S_IO_W_2_BASE_TO_TOP[6]),
    .AXIL_S_IO_W_2_BASE_TO_TOP7(AXIL_S_IO_W_2_BASE_TO_TOP[7]),
    .AXIL_S_IO_W_2_BASE_TO_TOP8(AXIL_S_IO_W_2_BASE_TO_TOP[8]),
    .AXIL_S_IO_W_2_BASE_TO_TOP9(AXIL_S_IO_W_2_BASE_TO_TOP[9]),
    .AXIL_S_IO_W_2_BASE_TO_TOP10(AXIL_S_IO_W_2_BASE_TO_TOP[10]),
    .AXIL_S_IO_W_2_BASE_TO_TOP11(AXIL_S_IO_W_2_BASE_TO_TOP[11]),
    .AXIL_S_IO_W_1_BASE_TO_TOP0(AXIL_S_IO_W_1_BASE_TO_TOP[0]),
    .AXIL_S_IO_W_1_BASE_TO_TOP1(AXIL_S_IO_W_1_BASE_TO_TOP[1]),
    .AXIL_S_IO_W_1_BASE_TO_TOP2(AXIL_S_IO_W_1_BASE_TO_TOP[2]),
    .AXIL_S_IO_W_1_BASE_TO_TOP3(AXIL_S_IO_W_1_BASE_TO_TOP[3]),
    .AXIL_S_IO_W_1_BASE_TO_TOP4(AXIL_S_IO_W_1_BASE_TO_TOP[4]),
    .AXIL_S_IO_W_1_BASE_TO_TOP5(AXIL_S_IO_W_1_BASE_TO_TOP[5]),
    .AXIL_S_IO_W_1_BASE_TO_TOP6(AXIL_S_IO_W_1_BASE_TO_TOP[6]),
    .AXIL_S_IO_W_1_BASE_TO_TOP7(AXIL_S_IO_W_1_BASE_TO_TOP[7]),
    .AXIL_S_IO_W_1_BASE_TO_TOP8(AXIL_S_IO_W_1_BASE_TO_TOP[8]),
    .AXIL_S_IO_W_1_BASE_TO_TOP9(AXIL_S_IO_W_1_BASE_TO_TOP[9]),
    .AXIL_S_IO_W_1_BASE_TO_TOP10(AXIL_S_IO_W_1_BASE_TO_TOP[10]),
    .AXIL_S_IO_W_1_BASE_TO_TOP11(AXIL_S_IO_W_1_BASE_TO_TOP[11]),
    .AXIL_S_IO_W_0_BASE_TO_TOP0(AXIL_S_IO_W_0_BASE_TO_TOP[0]),
    .AXIL_S_IO_W_0_BASE_TO_TOP1(AXIL_S_IO_W_0_BASE_TO_TOP[1]),
    .AXIL_S_IO_W_0_BASE_TO_TOP2(AXIL_S_IO_W_0_BASE_TO_TOP[2]),
    .AXIL_S_IO_W_0_BASE_TO_TOP3(AXIL_S_IO_W_0_BASE_TO_TOP[3]),
    .AXIL_S_IO_W_0_BASE_TO_TOP4(AXIL_S_IO_W_0_BASE_TO_TOP[4]),
    .AXIL_S_IO_W_0_BASE_TO_TOP5(AXIL_S_IO_W_0_BASE_TO_TOP[5]),
    .AXIL_S_IO_W_0_BASE_TO_TOP6(AXIL_S_IO_W_0_BASE_TO_TOP[6]),
    .AXIL_S_IO_W_0_BASE_TO_TOP7(AXIL_S_IO_W_0_BASE_TO_TOP[7]),
    .AXIL_S_IO_W_0_BASE_TO_TOP8(AXIL_S_IO_W_0_BASE_TO_TOP[8]),
    .AXIL_S_IO_W_0_BASE_TO_TOP9(AXIL_S_IO_W_0_BASE_TO_TOP[9]),
    .AXIL_S_IO_W_0_BASE_TO_TOP10(AXIL_S_IO_W_0_BASE_TO_TOP[10]),
    .AXIL_S_IO_W_0_BASE_TO_TOP11(AXIL_S_IO_W_0_BASE_TO_TOP[11]),
    .AXIL_S_FAB_AWREADY(AXIL_S_FAB_AWREADY),
    .AXIL_S_FAB_WREADY(AXIL_S_FAB_WREADY),
    .AXIL_S_FAB_BRESP0(AXIL_S_FAB_BRESP0),
    .AXIL_S_FAB_BRESP1(AXIL_S_FAB_BRESP1),
    .AXIL_S_FAB_BVALID(AXIL_S_FAB_BVALID),
    .AXIL_S_FAB_ARREADY(AXIL_S_FAB_ARREADY),
    .AXIL_S_FAB_RDATA0(AXIL_S_FAB_RDATA0),
    .AXIL_S_FAB_RDATA1(AXIL_S_FAB_RDATA1),
    .AXIL_S_FAB_RDATA2(AXIL_S_FAB_RDATA2),
    .AXIL_S_FAB_RDATA3(AXIL_S_FAB_RDATA3),
    .AXIL_S_FAB_RDATA4(AXIL_S_FAB_RDATA4),
    .AXIL_S_FAB_RDATA5(AXIL_S_FAB_RDATA5),
    .AXIL_S_FAB_RDATA6(AXIL_S_FAB_RDATA6),
    .AXIL_S_FAB_RDATA7(AXIL_S_FAB_RDATA7),
    .AXIL_S_FAB_RDATA8(AXIL_S_FAB_RDATA8),
    .AXIL_S_FAB_RDATA9(AXIL_S_FAB_RDATA9),
    .AXIL_S_FAB_RDATA10(AXIL_S_FAB_RDATA10),
    .AXIL_S_FAB_RDATA11(AXIL_S_FAB_RDATA11),
    .AXIL_S_FAB_RDATA12(AXIL_S_FAB_RDATA12),
    .AXIL_S_FAB_RDATA13(AXIL_S_FAB_RDATA13),
    .AXIL_S_FAB_RDATA14(AXIL_S_FAB_RDATA14),
    .AXIL_S_FAB_RDATA15(AXIL_S_FAB_RDATA15),
    .AXIL_S_FAB_RDATA16(AXIL_S_FAB_RDATA16),
    .AXIL_S_FAB_RDATA17(AXIL_S_FAB_RDATA17),
    .AXIL_S_FAB_RDATA18(AXIL_S_FAB_RDATA18),
    .AXIL_S_FAB_RDATA19(AXIL_S_FAB_RDATA19),
    .AXIL_S_FAB_RDATA20(AXIL_S_FAB_RDATA20),
    .AXIL_S_FAB_RDATA21(AXIL_S_FAB_RDATA21),
    .AXIL_S_FAB_RDATA22(AXIL_S_FAB_RDATA22),
    .AXIL_S_FAB_RDATA23(AXIL_S_FAB_RDATA23),
    .AXIL_S_FAB_RDATA24(AXIL_S_FAB_RDATA24),
    .AXIL_S_FAB_RDATA25(AXIL_S_FAB_RDATA25),
    .AXIL_S_FAB_RDATA26(AXIL_S_FAB_RDATA26),
    .AXIL_S_FAB_RDATA27(AXIL_S_FAB_RDATA27),
    .AXIL_S_FAB_RDATA28(AXIL_S_FAB_RDATA28),
    .AXIL_S_FAB_RDATA29(AXIL_S_FAB_RDATA29),
    .AXIL_S_FAB_RDATA30(AXIL_S_FAB_RDATA30),
    .AXIL_S_FAB_RDATA31(AXIL_S_FAB_RDATA31),
    .AXIL_S_FAB_RRESP0(AXIL_S_FAB_RRESP0),
    .AXIL_S_FAB_RRESP1(AXIL_S_FAB_RRESP1),
    .AXIL_S_FAB_RVALID(AXIL_S_FAB_RVALID),
    .AXIL_S_FAB_AWADDR0(AXIL_S_FAB_AWADDR0),
    .AXIL_S_FAB_AWADDR1(AXIL_S_FAB_AWADDR1),
    .AXIL_S_FAB_AWADDR2(AXIL_S_FAB_AWADDR2),
    .AXIL_S_FAB_AWADDR3(AXIL_S_FAB_AWADDR3),
    .AXIL_S_FAB_AWADDR4(AXIL_S_FAB_AWADDR4),
    .AXIL_S_FAB_AWADDR5(AXIL_S_FAB_AWADDR5),
    .AXIL_S_FAB_AWADDR6(AXIL_S_FAB_AWADDR6),
    .AXIL_S_FAB_AWADDR7(AXIL_S_FAB_AWADDR7),
    .AXIL_S_FAB_AWADDR8(AXIL_S_FAB_AWADDR8),
    .AXIL_S_FAB_AWADDR9(AXIL_S_FAB_AWADDR9),
    .AXIL_S_FAB_AWVALID(AXIL_S_FAB_AWVALID),
    .AXIL_S_FAB_WDATA0(AXIL_S_FAB_WDATA0),
    .AXIL_S_FAB_WDATA1(AXIL_S_FAB_WDATA1),
    .AXIL_S_FAB_WDATA2(AXIL_S_FAB_WDATA2),
    .AXIL_S_FAB_WDATA3(AXIL_S_FAB_WDATA3),
    .AXIL_S_FAB_WDATA4(AXIL_S_FAB_WDATA4),
    .AXIL_S_FAB_WDATA5(AXIL_S_FAB_WDATA5),
    .AXIL_S_FAB_WDATA6(AXIL_S_FAB_WDATA6),
    .AXIL_S_FAB_WDATA7(AXIL_S_FAB_WDATA7),
    .AXIL_S_FAB_WDATA8(AXIL_S_FAB_WDATA8),
    .AXIL_S_FAB_WDATA9(AXIL_S_FAB_WDATA9),
    .AXIL_S_FAB_WDATA10(AXIL_S_FAB_WDATA10),
    .AXIL_S_FAB_WDATA11(AXIL_S_FAB_WDATA11),
    .AXIL_S_FAB_WDATA12(AXIL_S_FAB_WDATA12),
    .AXIL_S_FAB_WDATA13(AXIL_S_FAB_WDATA13),
    .AXIL_S_FAB_WDATA14(AXIL_S_FAB_WDATA14),
    .AXIL_S_FAB_WDATA15(AXIL_S_FAB_WDATA15),
    .AXIL_S_FAB_WDATA16(AXIL_S_FAB_WDATA16),
    .AXIL_S_FAB_WDATA17(AXIL_S_FAB_WDATA17),
    .AXIL_S_FAB_WDATA18(AXIL_S_FAB_WDATA18),
    .AXIL_S_FAB_WDATA19(AXIL_S_FAB_WDATA19),
    .AXIL_S_FAB_WDATA20(AXIL_S_FAB_WDATA20),
    .AXIL_S_FAB_WDATA21(AXIL_S_FAB_WDATA21),
    .AXIL_S_FAB_WDATA22(AXIL_S_FAB_WDATA22),
    .AXIL_S_FAB_WDATA23(AXIL_S_FAB_WDATA23),
    .AXIL_S_FAB_WDATA24(AXIL_S_FAB_WDATA24),
    .AXIL_S_FAB_WDATA25(AXIL_S_FAB_WDATA25),
    .AXIL_S_FAB_WDATA26(AXIL_S_FAB_WDATA26),
    .AXIL_S_FAB_WDATA27(AXIL_S_FAB_WDATA27),
    .AXIL_S_FAB_WDATA28(AXIL_S_FAB_WDATA28),
    .AXIL_S_FAB_WDATA29(AXIL_S_FAB_WDATA29),
    .AXIL_S_FAB_WDATA30(AXIL_S_FAB_WDATA30),
    .AXIL_S_FAB_WDATA31(AXIL_S_FAB_WDATA31),
    .AXIL_S_FAB_WSTRB0(AXIL_S_FAB_WSTRB0),
    .AXIL_S_FAB_WSTRB1(AXIL_S_FAB_WSTRB1),
    .AXIL_S_FAB_WSTRB2(AXIL_S_FAB_WSTRB2),
    .AXIL_S_FAB_WSTRB3(AXIL_S_FAB_WSTRB3),
    .AXIL_S_FAB_WVALID(AXIL_S_FAB_WVALID),
    .AXIL_S_FAB_BREADY(AXIL_S_FAB_BREADY),
    .AXIL_S_FAB_ARADDR0(AXIL_S_FAB_ARADDR0),
    .AXIL_S_FAB_ARADDR1(AXIL_S_FAB_ARADDR1),
    .AXIL_S_FAB_ARADDR2(AXIL_S_FAB_ARADDR2),
    .AXIL_S_FAB_ARADDR3(AXIL_S_FAB_ARADDR3),
    .AXIL_S_FAB_ARADDR4(AXIL_S_FAB_ARADDR4),
    .AXIL_S_FAB_ARADDR5(AXIL_S_FAB_ARADDR5),
    .AXIL_S_FAB_ARADDR6(AXIL_S_FAB_ARADDR6),
    .AXIL_S_FAB_ARADDR7(AXIL_S_FAB_ARADDR7),
    .AXIL_S_FAB_ARADDR8(AXIL_S_FAB_ARADDR8),
    .AXIL_S_FAB_ARADDR9(AXIL_S_FAB_ARADDR9),
    .AXIL_S_FAB_ARVALID(AXIL_S_FAB_ARVALID),
    .AXIL_S_FAB_RREADY(AXIL_S_FAB_RREADY),
    .AXIL_S_IO_W_3_TOP_TO_BASE0(AXIL_S_IO_W_3_TOP_TO_BASE[0]),
    .AXIL_S_IO_W_3_TOP_TO_BASE1(AXIL_S_IO_W_3_TOP_TO_BASE[1]),
    .AXIL_S_IO_W_3_TOP_TO_BASE2(AXIL_S_IO_W_3_TOP_TO_BASE[2]),
    .AXIL_S_IO_W_3_TOP_TO_BASE3(AXIL_S_IO_W_3_TOP_TO_BASE[3]),
    .AXIL_S_IO_W_3_TOP_TO_BASE4(AXIL_S_IO_W_3_TOP_TO_BASE[4]),
    .AXIL_S_IO_W_3_TOP_TO_BASE5(AXIL_S_IO_W_3_TOP_TO_BASE[5]),
    .AXIL_S_IO_W_3_TOP_TO_BASE6(AXIL_S_IO_W_3_TOP_TO_BASE[6]),
    .AXIL_S_IO_W_3_TOP_TO_BASE7(AXIL_S_IO_W_3_TOP_TO_BASE[7]),
    .AXIL_S_IO_W_3_TOP_TO_BASE8(AXIL_S_IO_W_3_TOP_TO_BASE[8]),
    .AXIL_S_IO_W_3_TOP_TO_BASE9(AXIL_S_IO_W_3_TOP_TO_BASE[9]),
    .AXIL_S_IO_W_3_TOP_TO_BASE10(AXIL_S_IO_W_3_TOP_TO_BASE[10]),
    .AXIL_S_IO_W_3_TOP_TO_BASE11(AXIL_S_IO_W_3_TOP_TO_BASE[11]),
    .AXIL_S_IO_W_3_TOP_TO_BASE12(AXIL_S_IO_W_3_TOP_TO_BASE[12]),
    .AXIL_S_IO_W_3_TOP_TO_BASE13(AXIL_S_IO_W_3_TOP_TO_BASE[13]),
    .AXIL_S_IO_W_3_TOP_TO_BASE14(AXIL_S_IO_W_3_TOP_TO_BASE[14]),
    .AXIL_S_IO_W_3_TOP_TO_BASE15(AXIL_S_IO_W_3_TOP_TO_BASE[15]),
    .AXIL_S_IO_W_2_TOP_TO_BASE0(AXIL_S_IO_W_2_TOP_TO_BASE[0]),
    .AXIL_S_IO_W_2_TOP_TO_BASE1(AXIL_S_IO_W_2_TOP_TO_BASE[1]),
    .AXIL_S_IO_W_2_TOP_TO_BASE2(AXIL_S_IO_W_2_TOP_TO_BASE[2]),
    .AXIL_S_IO_W_2_TOP_TO_BASE3(AXIL_S_IO_W_2_TOP_TO_BASE[3]),
    .AXIL_S_IO_W_2_TOP_TO_BASE4(AXIL_S_IO_W_2_TOP_TO_BASE[4]),
    .AXIL_S_IO_W_2_TOP_TO_BASE5(AXIL_S_IO_W_2_TOP_TO_BASE[5]),
    .AXIL_S_IO_W_2_TOP_TO_BASE6(AXIL_S_IO_W_2_TOP_TO_BASE[6]),
    .AXIL_S_IO_W_2_TOP_TO_BASE7(AXIL_S_IO_W_2_TOP_TO_BASE[7]),
    .AXIL_S_IO_W_2_TOP_TO_BASE8(AXIL_S_IO_W_2_TOP_TO_BASE[8]),
    .AXIL_S_IO_W_2_TOP_TO_BASE9(AXIL_S_IO_W_2_TOP_TO_BASE[9]),
    .AXIL_S_IO_W_2_TOP_TO_BASE10(AXIL_S_IO_W_2_TOP_TO_BASE[10]),
    .AXIL_S_IO_W_2_TOP_TO_BASE11(AXIL_S_IO_W_2_TOP_TO_BASE[11]),
    .AXIL_S_IO_W_2_TOP_TO_BASE12(AXIL_S_IO_W_2_TOP_TO_BASE[12]),
    .AXIL_S_IO_W_2_TOP_TO_BASE13(AXIL_S_IO_W_2_TOP_TO_BASE[13]),
    .AXIL_S_IO_W_2_TOP_TO_BASE14(AXIL_S_IO_W_2_TOP_TO_BASE[14]),
    .AXIL_S_IO_W_2_TOP_TO_BASE15(AXIL_S_IO_W_2_TOP_TO_BASE[15]),
    .AXIL_S_IO_W_1_TOP_TO_BASE0(AXIL_S_IO_W_1_TOP_TO_BASE[0]),
    .AXIL_S_IO_W_1_TOP_TO_BASE1(AXIL_S_IO_W_1_TOP_TO_BASE[1]),
    .AXIL_S_IO_W_1_TOP_TO_BASE2(AXIL_S_IO_W_1_TOP_TO_BASE[2]),
    .AXIL_S_IO_W_1_TOP_TO_BASE3(AXIL_S_IO_W_1_TOP_TO_BASE[3]),
    .AXIL_S_IO_W_1_TOP_TO_BASE4(AXIL_S_IO_W_1_TOP_TO_BASE[4]),
    .AXIL_S_IO_W_1_TOP_TO_BASE5(AXIL_S_IO_W_1_TOP_TO_BASE[5]),
    .AXIL_S_IO_W_1_TOP_TO_BASE6(AXIL_S_IO_W_1_TOP_TO_BASE[6]),
    .AXIL_S_IO_W_1_TOP_TO_BASE7(AXIL_S_IO_W_1_TOP_TO_BASE[7]),
    .AXIL_S_IO_W_1_TOP_TO_BASE8(AXIL_S_IO_W_1_TOP_TO_BASE[8]),
    .AXIL_S_IO_W_1_TOP_TO_BASE9(AXIL_S_IO_W_1_TOP_TO_BASE[9]),
    .AXIL_S_IO_W_1_TOP_TO_BASE10(AXIL_S_IO_W_1_TOP_TO_BASE[10]),
    .AXIL_S_IO_W_1_TOP_TO_BASE11(AXIL_S_IO_W_1_TOP_TO_BASE[11]),
    .AXIL_S_IO_W_1_TOP_TO_BASE12(AXIL_S_IO_W_1_TOP_TO_BASE[12]),
    .AXIL_S_IO_W_1_TOP_TO_BASE13(AXIL_S_IO_W_1_TOP_TO_BASE[13]),
    .AXIL_S_IO_W_1_TOP_TO_BASE14(AXIL_S_IO_W_1_TOP_TO_BASE[14]),
    .AXIL_S_IO_W_1_TOP_TO_BASE15(AXIL_S_IO_W_1_TOP_TO_BASE[15]),
    .AXIL_S_IO_W_0_TOP_TO_BASE0(AXIL_S_IO_W_0_TOP_TO_BASE[0]),
    .AXIL_S_IO_W_0_TOP_TO_BASE1(AXIL_S_IO_W_0_TOP_TO_BASE[1]),
    .AXIL_S_IO_W_0_TOP_TO_BASE2(AXIL_S_IO_W_0_TOP_TO_BASE[2]),
    .AXIL_S_IO_W_0_TOP_TO_BASE3(AXIL_S_IO_W_0_TOP_TO_BASE[3]),
    .AXIL_S_IO_W_0_TOP_TO_BASE4(AXIL_S_IO_W_0_TOP_TO_BASE[4]),
    .AXIL_S_IO_W_0_TOP_TO_BASE5(AXIL_S_IO_W_0_TOP_TO_BASE[5]),
    .AXIL_S_IO_W_0_TOP_TO_BASE6(AXIL_S_IO_W_0_TOP_TO_BASE[6]),
    .AXIL_S_IO_W_0_TOP_TO_BASE7(AXIL_S_IO_W_0_TOP_TO_BASE[7]),
    .AXIL_S_IO_W_0_TOP_TO_BASE8(AXIL_S_IO_W_0_TOP_TO_BASE[8]),
    .AXIL_S_IO_W_0_TOP_TO_BASE9(AXIL_S_IO_W_0_TOP_TO_BASE[9]),
    .AXIL_S_IO_W_0_TOP_TO_BASE10(AXIL_S_IO_W_0_TOP_TO_BASE[10]),
    .AXIL_S_IO_W_0_TOP_TO_BASE11(AXIL_S_IO_W_0_TOP_TO_BASE[11]),
    .AXIL_S_IO_W_0_TOP_TO_BASE12(AXIL_S_IO_W_0_TOP_TO_BASE[12]),
    .AXIL_S_IO_W_0_TOP_TO_BASE13(AXIL_S_IO_W_0_TOP_TO_BASE[13]),
    .AXIL_S_IO_W_0_TOP_TO_BASE14(AXIL_S_IO_W_0_TOP_TO_BASE[14]),
    .AXIL_S_IO_W_0_TOP_TO_BASE15(AXIL_S_IO_W_0_TOP_TO_BASE[15]),
    .ConfigBits(ST_ConfigBits[6-1:0]),
    .ConfigBits_N(ST_ConfigBits_N[6-1:0])
);

AXIL_S_BEL Inst_ST_AXIL_S_AXIL_S_BEL (
    .FAB_AWREADY(AXIL_S_FAB_AWREADY),
    .FAB_WREADY(AXIL_S_FAB_WREADY),
    .FAB_BRESP({AXIL_S_FAB_BRESP1, AXIL_S_FAB_BRESP0}),
    .FAB_BVALID(AXIL_S_FAB_BVALID),
    .FAB_ARREADY(AXIL_S_FAB_ARREADY),
    .FAB_RDATA({AXIL_S_FAB_RDATA31, AXIL_S_FAB_RDATA30, AXIL_S_FAB_RDATA29, AXIL_S_FAB_RDATA28, AXIL_S_FAB_RDATA27, AXIL_S_FAB_RDATA26, AXIL_S_FAB_RDATA25, AXIL_S_FAB_RDATA24, AXIL_S_FAB_RDATA23, AXIL_S_FAB_RDATA22, AXIL_S_FAB_RDATA21, AXIL_S_FAB_RDATA20, AXIL_S_FAB_RDATA19, AXIL_S_FAB_RDATA18, AXIL_S_FAB_RDATA17, AXIL_S_FAB_RDATA16, AXIL_S_FAB_RDATA15, AXIL_S_FAB_RDATA14, AXIL_S_FAB_RDATA13, AXIL_S_FAB_RDATA12, AXIL_S_FAB_RDATA11, AXIL_S_FAB_RDATA10, AXIL_S_FAB_RDATA9, AXIL_S_FAB_RDATA8, AXIL_S_FAB_RDATA7, AXIL_S_FAB_RDATA6, AXIL_S_FAB_RDATA5, AXIL_S_FAB_RDATA4, AXIL_S_FAB_RDATA3, AXIL_S_FAB_RDATA2, AXIL_S_FAB_RDATA1, AXIL_S_FAB_RDATA0}),
    .FAB_RRESP({AXIL_S_FAB_RRESP1, AXIL_S_FAB_RRESP0}),
    .FAB_RVALID(AXIL_S_FAB_RVALID),
    .FAB_AWADDR({AXIL_S_FAB_AWADDR9, AXIL_S_FAB_AWADDR8, AXIL_S_FAB_AWADDR7, AXIL_S_FAB_AWADDR6, AXIL_S_FAB_AWADDR5, AXIL_S_FAB_AWADDR4, AXIL_S_FAB_AWADDR3, AXIL_S_FAB_AWADDR2, AXIL_S_FAB_AWADDR1, AXIL_S_FAB_AWADDR0}),
    .FAB_AWVALID(AXIL_S_FAB_AWVALID),
    .FAB_WDATA({AXIL_S_FAB_WDATA31, AXIL_S_FAB_WDATA30, AXIL_S_FAB_WDATA29, AXIL_S_FAB_WDATA28, AXIL_S_FAB_WDATA27, AXIL_S_FAB_WDATA26, AXIL_S_FAB_WDATA25, AXIL_S_FAB_WDATA24, AXIL_S_FAB_WDATA23, AXIL_S_FAB_WDATA22, AXIL_S_FAB_WDATA21, AXIL_S_FAB_WDATA20, AXIL_S_FAB_WDATA19, AXIL_S_FAB_WDATA18, AXIL_S_FAB_WDATA17, AXIL_S_FAB_WDATA16, AXIL_S_FAB_WDATA15, AXIL_S_FAB_WDATA14, AXIL_S_FAB_WDATA13, AXIL_S_FAB_WDATA12, AXIL_S_FAB_WDATA11, AXIL_S_FAB_WDATA10, AXIL_S_FAB_WDATA9, AXIL_S_FAB_WDATA8, AXIL_S_FAB_WDATA7, AXIL_S_FAB_WDATA6, AXIL_S_FAB_WDATA5, AXIL_S_FAB_WDATA4, AXIL_S_FAB_WDATA3, AXIL_S_FAB_WDATA2, AXIL_S_FAB_WDATA1, AXIL_S_FAB_WDATA0}),
    .FAB_WSTRB({AXIL_S_FAB_WSTRB3, AXIL_S_FAB_WSTRB2, AXIL_S_FAB_WSTRB1, AXIL_S_FAB_WSTRB0}),
    .FAB_WVALID(AXIL_S_FAB_WVALID),
    .FAB_BREADY(AXIL_S_FAB_BREADY),
    .FAB_ARADDR({AXIL_S_FAB_ARADDR9, AXIL_S_FAB_ARADDR8, AXIL_S_FAB_ARADDR7, AXIL_S_FAB_ARADDR6, AXIL_S_FAB_ARADDR5, AXIL_S_FAB_ARADDR4, AXIL_S_FAB_ARADDR3, AXIL_S_FAB_ARADDR2, AXIL_S_FAB_ARADDR1, AXIL_S_FAB_ARADDR0}),
    .FAB_ARVALID(AXIL_S_FAB_ARVALID),
    .FAB_RREADY(AXIL_S_FAB_RREADY),
    .SOC_AWADDR({AXIL_S_SOC_AWADDR9, AXIL_S_SOC_AWADDR8, AXIL_S_SOC_AWADDR7, AXIL_S_SOC_AWADDR6, AXIL_S_SOC_AWADDR5, AXIL_S_SOC_AWADDR4, AXIL_S_SOC_AWADDR3, AXIL_S_SOC_AWADDR2, AXIL_S_SOC_AWADDR1, AXIL_S_SOC_AWADDR0}),
    .SOC_AWVALID(AXIL_S_SOC_AWVALID),
    .SOC_WDATA({AXIL_S_SOC_WDATA31, AXIL_S_SOC_WDATA30, AXIL_S_SOC_WDATA29, AXIL_S_SOC_WDATA28, AXIL_S_SOC_WDATA27, AXIL_S_SOC_WDATA26, AXIL_S_SOC_WDATA25, AXIL_S_SOC_WDATA24, AXIL_S_SOC_WDATA23, AXIL_S_SOC_WDATA22, AXIL_S_SOC_WDATA21, AXIL_S_SOC_WDATA20, AXIL_S_SOC_WDATA19, AXIL_S_SOC_WDATA18, AXIL_S_SOC_WDATA17, AXIL_S_SOC_WDATA16, AXIL_S_SOC_WDATA15, AXIL_S_SOC_WDATA14, AXIL_S_SOC_WDATA13, AXIL_S_SOC_WDATA12, AXIL_S_SOC_WDATA11, AXIL_S_SOC_WDATA10, AXIL_S_SOC_WDATA9, AXIL_S_SOC_WDATA8, AXIL_S_SOC_WDATA7, AXIL_S_SOC_WDATA6, AXIL_S_SOC_WDATA5, AXIL_S_SOC_WDATA4, AXIL_S_SOC_WDATA3, AXIL_S_SOC_WDATA2, AXIL_S_SOC_WDATA1, AXIL_S_SOC_WDATA0}),
    .SOC_WSTRB({AXIL_S_SOC_WSTRB3, AXIL_S_SOC_WSTRB2, AXIL_S_SOC_WSTRB1, AXIL_S_SOC_WSTRB0}),
    .SOC_WVALID(AXIL_S_SOC_WVALID),
    .SOC_BREADY(AXIL_S_SOC_BREADY),
    .SOC_ARADDR({AXIL_S_SOC_ARADDR9, AXIL_S_SOC_ARADDR8, AXIL_S_SOC_ARADDR7, AXIL_S_SOC_ARADDR6, AXIL_S_SOC_ARADDR5, AXIL_S_SOC_ARADDR4, AXIL_S_SOC_ARADDR3, AXIL_S_SOC_ARADDR2, AXIL_S_SOC_ARADDR1, AXIL_S_SOC_ARADDR0}),
    .SOC_ARVALID(AXIL_S_SOC_ARVALID),
    .SOC_RREADY(AXIL_S_SOC_RREADY),
    .SOC_AWREADY(AXIL_S_SOC_AWREADY),
    .SOC_WREADY(AXIL_S_SOC_WREADY),
    .SOC_BRESP({AXIL_S_SOC_BRESP1, AXIL_S_SOC_BRESP0}),
    .SOC_BVALID(AXIL_S_SOC_BVALID),
    .SOC_ARREADY(AXIL_S_SOC_ARREADY),
    .SOC_RDATA({AXIL_S_SOC_RDATA31, AXIL_S_SOC_RDATA30, AXIL_S_SOC_RDATA29, AXIL_S_SOC_RDATA28, AXIL_S_SOC_RDATA27, AXIL_S_SOC_RDATA26, AXIL_S_SOC_RDATA25, AXIL_S_SOC_RDATA24, AXIL_S_SOC_RDATA23, AXIL_S_SOC_RDATA22, AXIL_S_SOC_RDATA21, AXIL_S_SOC_RDATA20, AXIL_S_SOC_RDATA19, AXIL_S_SOC_RDATA18, AXIL_S_SOC_RDATA17, AXIL_S_SOC_RDATA16, AXIL_S_SOC_RDATA15, AXIL_S_SOC_RDATA14, AXIL_S_SOC_RDATA13, AXIL_S_SOC_RDATA12, AXIL_S_SOC_RDATA11, AXIL_S_SOC_RDATA10, AXIL_S_SOC_RDATA9, AXIL_S_SOC_RDATA8, AXIL_S_SOC_RDATA7, AXIL_S_SOC_RDATA6, AXIL_S_SOC_RDATA5, AXIL_S_SOC_RDATA4, AXIL_S_SOC_RDATA3, AXIL_S_SOC_RDATA2, AXIL_S_SOC_RDATA1, AXIL_S_SOC_RDATA0}),
    .SOC_RRESP({AXIL_S_SOC_RRESP1, AXIL_S_SOC_RRESP0}),
    .SOC_RVALID(AXIL_S_SOC_RVALID)
);

endmodule