# =============================================================================
# CrocoScale SoC -- FABulous Tile Library (9x16 Architecture)
# =============================================================================
-f fabulous_bels.f

# --- Sub-tile Switch Matrices & Config Memories ---
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_0/AXIL_S_IO_W_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_0/AXIL_S_IO_W_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_1/AXIL_S_IO_W_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_1/AXIL_S_IO_W_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_2/AXIL_S_IO_W_2_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_2/AXIL_S_IO_W_2_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_3/AXIL_S_IO_W_3_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_3/AXIL_S_IO_W_3_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_4/AXIL_S_IO_W_4_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_4/AXIL_S_IO_W_4_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_5/AXIL_S_IO_W_5_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_5/AXIL_S_IO_W_5_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_0/AXI_M_IO_W_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_0/AXI_M_IO_W_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_1/AXI_M_IO_W_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_1/AXI_M_IO_W_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_2/AXI_M_IO_W_2_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_2/AXI_M_IO_W_2_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_3/AXI_M_IO_W_3_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_3/AXI_M_IO_W_3_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_4/AXI_M_IO_W_4_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_4/AXI_M_IO_W_4_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_5/AXI_M_IO_W_5_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_5/AXI_M_IO_W_5_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_6/AXI_M_IO_W_6_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_6/AXI_M_IO_W_6_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_7/AXI_M_IO_W_7_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_7/AXI_M_IO_W_7_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_8/AXI_M_IO_W_8_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_8/AXI_M_IO_W_8_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_9/AXI_M_IO_W_9_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_9/AXI_M_IO_W_9_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_0/EXT_PMOD_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_0/EXT_PMOD_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_1/EXT_PMOD_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_1/EXT_PMOD_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_0/NPU_ACCUM_N_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_0/NPU_ACCUM_N_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_1/NPU_ACCUM_N_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_1/NPU_ACCUM_N_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_2/NPU_ACCUM_N_2_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_2/NPU_ACCUM_N_2_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_3/NPU_ACCUM_N_3_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_3/NPU_ACCUM_N_3_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_4/NPU_ACCUM_N_4_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_4/NPU_ACCUM_N_4_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_0/NPU_ACCUM_S_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_0/NPU_ACCUM_S_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_1/NPU_ACCUM_S_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_1/NPU_ACCUM_S_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_2/NPU_ACCUM_S_2_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_2/NPU_ACCUM_S_2_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_3/NPU_ACCUM_S_3_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_3/NPU_ACCUM_S_3_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_4/NPU_ACCUM_S_4_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_4/NPU_ACCUM_S_4_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_0/NPU_CTRL_CFG_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_0/NPU_CTRL_CFG_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_1/NPU_CTRL_CFG_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_1/NPU_CTRL_CFG_1_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_0/NPU_SLICE_0_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_0/NPU_SLICE_0_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_1/NPU_SLICE_1_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_1/NPU_SLICE_1_switch_matrix.v

# --- Sub-tile Tops ---
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_0/AXIL_S_IO_W_0.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_1/AXIL_S_IO_W_1.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_2/AXIL_S_IO_W_2.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_3/AXIL_S_IO_W_3.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_4/AXIL_S_IO_W_4.v
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_5/AXIL_S_IO_W_5.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_0/AXI_M_IO_W_0.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_1/AXI_M_IO_W_1.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_2/AXI_M_IO_W_2.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_3/AXI_M_IO_W_3.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_4/AXI_M_IO_W_4.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_5/AXI_M_IO_W_5.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_6/AXI_M_IO_W_6.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_7/AXI_M_IO_W_7.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_8/AXI_M_IO_W_8.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_9/AXI_M_IO_W_9.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_0/EXT_PMOD_0.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_1/EXT_PMOD_1.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_0/NPU_ACCUM_N_0.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_1/NPU_ACCUM_N_1.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_2/NPU_ACCUM_N_2.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_3/NPU_ACCUM_N_3.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_4/NPU_ACCUM_N_4.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_0/NPU_ACCUM_S_0.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_1/NPU_ACCUM_S_1.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_2/NPU_ACCUM_S_2.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_3/NPU_ACCUM_S_3.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_4/NPU_ACCUM_S_4.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_0/NPU_CTRL_CFG_0.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_1/NPU_CTRL_CFG_1.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_0/NPU_SLICE_0.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_1/NPU_SLICE_1.v

# --- Super-tile Switch Matrices & Config Memories ---
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/LUT4AB/LUT4AB_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/LUT4AB/LUT4AB_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/N_term_RAM_IO/N_term_RAM_IO_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/SOC_DEBUG_IO/SOC_DEBUG_IO_ConfigMem.v
FABulousProject/CrocoScale_Fabric/Tile/SOC_DEBUG_IO/SOC_DEBUG_IO_switch_matrix.v
FABulousProject/CrocoScale_Fabric/Tile/S_term_RAM_IO/S_term_RAM_IO_switch_matrix.v

# --- Super-tile Tops ---
FABulousProject/CrocoScale_Fabric/Tile/AXIL_S_IO_W/AXIL_S_IO_W.v
FABulousProject/CrocoScale_Fabric/Tile/AXI_M_IO_W/AXI_M_IO_W.v
FABulousProject/CrocoScale_Fabric/Tile/EXT_PMOD/EXT_PMOD.v
FABulousProject/CrocoScale_Fabric/Tile/LUT4AB/LUT4AB.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_N/NPU_ACCUM_N.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_ACCUM_S/NPU_ACCUM_S.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_CTRL_CFG/NPU_CTRL_CFG.v
FABulousProject/CrocoScale_Fabric/Tile/NPU_SLICE/NPU_SLICE.v
FABulousProject/CrocoScale_Fabric/Tile/N_term_RAM_IO/N_term_RAM_IO.v
FABulousProject/CrocoScale_Fabric/Tile/SOC_DEBUG_IO/SOC_DEBUG_IO.v
FABulousProject/CrocoScale_Fabric/Tile/S_term_RAM_IO/S_term_RAM_IO.v

