SOFT_LOGIC/minimal_3x3/npu_minimal_regs.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_dma.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_sequencer.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_controller.sv
SOFT_LOGIC/full/npu_dma_reader.sv
SOFT_LOGIC/full/npu_seq_fsm.sv
SOFT_LOGIC/full/npu_seq_weight_swap.sv
SOFT_LOGIC/full/npu_seq_psum_sched.sv
SOFT_LOGIC/full/npu_seq_addr_3x3.sv
SOFT_LOGIC/full/npu_seq_addr_1x1.sv
SOFT_LOGIC/full/npu_dma_drainer.sv
SOFT_LOGIC/full/npu_full_regs.sv
SOFT_LOGIC/full/npu_full_sequencer.sv
SOFT_LOGIC/full/npu_full_dma.sv
SOFT_LOGIC/full/npu_full_controller.sv
