SOFT_LOGIC/minimal_3x3/npu_minimal_regs.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_dma.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_sequencer.sv
SOFT_LOGIC/minimal_3x3/npu_minimal_controller.sv
SOFT_LOGIC/full/npu_axil_csr.sv
SOFT_LOGIC/full/npu_axi_reader.sv
SOFT_LOGIC/full/npu_axi_writer.sv
SOFT_LOGIC/full/npu_axi_dma.sv
SOFT_LOGIC/full/npu_seq_fsm.sv
SOFT_LOGIC/full/npu_seq_weights.sv
SOFT_LOGIC/full/npu_seq_psum.sv
SOFT_LOGIC/full/npu_seq_preload.sv
SOFT_LOGIC/full/npu_seq_addr_3x3.sv
SOFT_LOGIC/full/npu_seq_addr_1x1.sv
SOFT_LOGIC/full/npu_seq_arbiter.sv
SOFT_LOGIC/full/npu_full_sequencer.sv
SOFT_LOGIC/full/npu_full_controller.sv
